// ════════════════════════════════════════════════════════════════════════
//  A-MES ERD Data · 149 tables across 10 modules
//  Column format: [name, type, flag]
//    flag = '' | 'PK' | 'FK:Target.Column'
//  External FKs render as dashed chips automatically.
// ════════════════════════════════════════════════════════════════════════
const ERD_DATA = {

// ──────────────────────────────────────────────────────────────────────
// MD · Master Data (33 tables, natural-key PKs)
// ──────────────────────────────────────────────────────────────────────
MD: { cols: 4, tables: [
  {name:'MD_Item', ko:'품목 (MD-01)', cols:[
    ['ItemNo','VARCHAR(20)','PK'],
    ['ItemName','NVARCHAR(80)',''],
    ['ItemNameEN','NVARCHAR(80)',''],
    ['ItemType','VARCHAR(10)',''],
    ['ItemCategory','VARCHAR(30)',''],
    ['DefaultUOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['RoutingType','CHAR(1)',''],
    ['MinStock','DECIMAL(14,4)',''],
    ['MaxStock','DECIMAL(14,4)',''],
    ['SafetyStock','DECIMAL(14,4)',''],
    ['UnitCost','DECIMAL(14,2)',''],
    ['CustItemNoSAV','VARCHAR(30)',''],
    ['CustItemNoGEO','VARCHAR(30)',''],
    ['DrawingNo','VARCHAR(30)',''],
    ['ActiveFlag','BIT',''],
    ['CreatedBy','VARCHAR(20)',''],
    ['CreatedTS','DATETIME2',''],
    ['ModifiedTS','DATETIME2','']
  ]},
  {name:'MD_Bom', ko:'BOM (MD-02)', cols:[
    ['BOMID','VARCHAR(24)','PK'],
    ['ParentItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['CompItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['BOMLevel','INT',''],
    ['QtyPer','DECIMAL(12,4)',''],
    ['UOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['ScrapPct','DECIMAL(5,2)',''],
    ['VersionID','VARCHAR(24)','FK:MD_BomVersion.VersionID'],
    ['Position','INT',''],
    ['Note','NVARCHAR(120)',''],
    ['ActiveFlag','BIT',''],
    ['CreatedTS','DATETIME2','']
  ]},
  {name:'MD_BomVersion', ko:'BOM 버전 (MD-03)', cols:[
    ['VersionID','VARCHAR(24)','PK'],
    ['RootItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['VersionNo','VARCHAR(10)',''],
    ['EffFrom','DATE',''],
    ['EffTo','DATE',''],
    ['ChangeType','VARCHAR(16)',''],
    ['ChangeReason','NVARCHAR(200)',''],
    ['RequestedBy','VARCHAR(20)',''],
    ['ApprovedBy','VARCHAR(20)',''],
    ['ApprovedTS','DATETIME2',''],
    ['Status','VARCHAR(12)','']
  ]},
  {name:'MD_Bop', ko:'BOP 라우팅 (MD-04)', cols:[
    ['BOPID','VARCHAR(24)','PK'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['RoutingType','CHAR(1)',''],
    ['StepSeq','INT',''],
    ['ProcessCode','VARCHAR(10)',''],
    ['WorkCenterID','VARCHAR(20)','FK:MD_WorkCenter.WCID'],
    ['StdCycleTime','DECIMAL(8,2)',''],
    ['StdSetupTime','DECIMAL(8,2)',''],
    ['QcRequiredFlag','BIT',''],
    ['StepDescription','NVARCHAR(120)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_WorkCenter', ko:'작업장 (MD-05)', cols:[
    ['WCID','VARCHAR(20)','PK'],
    ['WCName','NVARCHAR(50)',''],
    ['ProcessType','VARCHAR(16)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['DailyCapacity','INT',''],
    ['StdManpower','INT',''],
    ['CostCenterCode','VARCHAR(20)',''],
    ['LocationDesc','NVARCHAR(60)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_InspectionStandard', ko:'검사 기준 (MD-06)', cols:[
    ['InspStdID','VARCHAR(20)','PK'],
    ['ItemID','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['ProcessCode','VARCHAR(10)',''],
    ['InspType','VARCHAR(10)',''],
    ['CharName','NVARCHAR(60)',''],
    ['SpecNominal','DECIMAL(12,4)',''],
    ['SpecLSL','DECIMAL(12,4)',''],
    ['SpecUSL','DECIMAL(12,4)',''],
    ['UOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['SamplingPlan','VARCHAR(20)',''],
    ['InspMethod','NVARCHAR(40)',''],
    ['IsCTQ','BIT',''],
    ['EffectiveDate','DATE',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_Vendor', ko:'거래선 (MD-07)', cols:[
    ['VendorID','VARCHAR(20)','PK'],
    ['VendorName','NVARCHAR(80)',''],
    ['VendorType','VARCHAR(10)',''],
    ['VendorCategory','NVARCHAR(30)',''],
    ['BizRegNo','VARCHAR(20)',''],
    ['ContactPerson','NVARCHAR(40)',''],
    ['Phone','VARCHAR(20)',''],
    ['Email','VARCHAR(60)',''],
    ['ScmURL','VARCHAR(255)',''],
    ['EdiFlag','BIT',''],
    ['OtdTargetRate','DECIMAL(5,2)',''],
    ['PaymentTerms','VARCHAR(30)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_Equipment', ko:'설비 (MD-08)', cols:[
    ['EquipID','VARCHAR(20)','PK'],
    ['EquipName','NVARCHAR(50)',''],
    ['EquipType','VARCHAR(16)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['WCID','VARCHAR(20)','FK:MD_WorkCenter.WCID'],
    ['MakerModel','NVARCHAR(60)',''],
    ['InstallDate','DATE',''],
    ['TheoreticalCycle','DECIMAL(8,2)',''],
    ['TargetOEE','DECIMAL(5,2)',''],
    ['MoldCompatJSON','NVARCHAR(MAX)',''],
    ['PlcAddress','VARCHAR(40)',''],
    ['Status','VARCHAR(8)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_Mold', ko:'금형 (MD-09)', cols:[
    ['MoldID','VARCHAR(20)','PK'],
    ['MoldName','NVARCHAR(50)',''],
    ['CompatItemsJSON','NVARCHAR(MAX)',''],
    ['RatedShots','INT',''],
    ['CurrentShots','INT',''],
    ['CavityCount','INT',''],
    ['Tonnage','INT',''],
    ['StorageLoc','VARCHAR(20)',''],
    ['LastMaintDate','DATE',''],
    ['Status','VARCHAR(10)','']
  ]},
  {name:'MD_PaintFabric', ko:'도료·원단 LOT (MD-10)', cols:[
    ['MatLotID','VARCHAR(24)','PK'],
    ['MatCode','VARCHAR(20)',''],
    ['MatName','NVARCHAR(60)',''],
    ['MatType','VARCHAR(14)',''],
    ['LotNo','VARCHAR(24)',''],
    ['SupplierID','VARCHAR(20)','FK:MD_Vendor.VendorID'],
    ['UOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['QtyOnHand','DECIMAL(12,3)',''],
    ['ReceiptDate','DATE',''],
    ['ExpDate','DATE',''],
    ['StorageReq','NVARCHAR(40)',''],
    ['Status','VARCHAR(10)','']
  ]},
  {name:'MD_ShipmentDest', ko:'출하처 (MD-11)', cols:[
    ['ShipDestID','VARCHAR(20)','PK'],
    ['CustomerID','VARCHAR(20)','FK:MD_Customer.CustomerID'],
    ['DestName','NVARCHAR(80)',''],
    ['DestType','VARCHAR(10)',''],
    ['Address','NVARCHAR(200)',''],
    ['Country','CHAR(3)',''],
    ['DeliveryDock','VARCHAR(20)',''],
    ['LeadTimeDays','INT',''],
    ['DefaultCarrier','NVARCHAR(40)',''],
    ['DeliveryWindow','VARCHAR(40)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_Customer', ko:'고객사 (MD-12)', cols:[
    ['CustomerID','VARCHAR(20)','PK'],
    ['CustomerCode','VARCHAR(20)',''],
    ['CustomerName','NVARCHAR(80)',''],
    ['CustomerNameEn','NVARCHAR(80)',''],
    ['CustomerType','VARCHAR(12)',''],
    ['BizRegNo','VARCHAR(20)',''],
    ['Country','CHAR(3)',''],
    ['ContactPerson','NVARCHAR(40)',''],
    ['ContactPhone','VARCHAR(20)',''],
    ['ContactEmail','VARCHAR(60)',''],
    ['EDIFlag','BIT',''],
    ['CurrencyCode','CHAR(3)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_Uom', ko:'단위 (MD-13)', cols:[
    ['UOMCode','VARCHAR(10)','PK'],
    ['UOMName','NVARCHAR(30)',''],
    ['UOMCategory','VARCHAR(10)',''],
    ['BaseFlag','BIT',''],
    ['BaseUOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['ConvFactor','DECIMAL(18,8)',''],
    ['DecimalPrec','INT',''],
    ['Symbol','NVARCHAR(8)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_Calendar', ko:'공장 캘린더 (MD-14)', cols:[
    ['PlantID','VARCHAR(10)','PK'],
    ['CalendarDate','DATE','PK'],
    ['DayType','VARCHAR(10)',''],
    ['HolidayName','NVARCHAR(40)',''],
    ['ShiftCount','INT',''],
    ['ShiftPattern','VARCHAR(20)',''],
    ['WorkHours','DECIMAL(5,2)',''],
    ['CalendarYear','INT',''],
    ['Note','NVARCHAR(120)','']
  ]},
  {name:'MD_Jig', ko:'지그 (MD-15)', cols:[
    ['JigID','VARCHAR(20)','PK'],
    ['JigName','NVARCHAR(50)',''],
    ['HangerCount','INT',''],
    ['CompatItemsJSON','NVARCHAR(MAX)',''],
    ['RatedCycle','INT',''],
    ['CycleCount','INT',''],
    ['ReadFailRate','DECIMAL(5,2)',''],
    ['HealthStatus','VARCHAR(8)',''],
    ['LastServiceDate','DATE',''],
    ['LastUsedTS','DATETIME2',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_RfidTag', ko:'RFID 태그 (MD-16)', cols:[
    ['TagID','VARCHAR(24)','PK'],
    ['EPC','VARCHAR(32)',''],
    ['JigID','VARCHAR(20)','FK:MD_Jig.JigID'],
    ['TagRole','VARCHAR(6)',''],
    ['HeatRating','INT',''],
    ['MountPos','NVARCHAR(20)',''],
    ['InstallDate','DATE',''],
    ['CycleCount','INT',''],
    ['ReplaceSchedule','DATE',''],
    ['Status','VARCHAR(10)','']
  ]},
  {name:'MD_RalColor', ko:'RAL 컬러 (MD-17)', cols:[
    ['RALCode','VARCHAR(12)','PK'],
    ['ColorName','NVARCHAR(40)',''],
    ['HexValue','VARCHAR(7)',''],
    ['CurrentPowderLot','VARCHAR(24)','FK:MD_PaintFabric.MatLotID'],
    ['CureTemp','INT',''],
    ['CureDuration','INT',''],
    ['ElectroV','INT',''],
    ['ParticleUm','DECIMAL(5,1)',''],
    ['CustomerMapJSON','NVARCHAR(MAX)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_Oven', ko:'오븐 (MD-18)', cols:[
    ['OvenID','VARCHAR(20)','PK'],
    ['OvenName','NVARCHAR(50)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['ZoneCount','INT',''],
    ['TargetTemp','INT',''],
    ['Tolerance','INT',''],
    ['DwellSec','INT',''],
    ['ConveyorSpeed','DECIMAL(6,2)',''],
    ['MaxLoadKg','DECIMAL(8,1)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_RfidReader', ko:'RFID 리더 (MD-19)', cols:[
    ['ReaderID','VARCHAR(20)','PK'],
    ['ReaderName','NVARCHAR(50)',''],
    ['GateLocation','VARCHAR(4)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['AntennaCount','INT',''],
    ['PowerDbm','INT',''],
    ['PeTriggerFlag','BIT',''],
    ['WindowMs','INT',''],
    ['IpAddress','VARCHAR(45)',''],
    ['FirmwareVer','VARCHAR(16)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_Line', ko:'생산 라인 (MD-20)', cols:[
    ['LineID','VARCHAR(20)','PK'],
    ['LineName','NVARCHAR(50)',''],
    ['LineType','VARCHAR(16)',''],
    ['PlantID','VARCHAR(10)',''],
    ['DefaultWCID','VARCHAR(20)','FK:MD_WorkCenter.WCID'],
    ['DailyCap','INT',''],
    ['ShiftPattern','VARCHAR(20)',''],
    ['RfidEnabledFlag','BIT',''],
    ['Status','VARCHAR(10)','']
  ]},
  {name:'MD_DefectCode', ko:'불량 코드 (MD-21)', cols:[
    ['DefectCode','VARCHAR(16)','PK'],
    ['DefectName','NVARCHAR(60)',''],
    ['DefectNameEn','NVARCHAR(60)',''],
    ['ProcessCode','VARCHAR(10)',''],
    ['DefectCategory','VARCHAR(14)',''],
    ['SeverityLevel','VARCHAR(8)',''],
    ['DispositionDefault','VARCHAR(10)',''],
    ['DefaultCauseCode','VARCHAR(16)','FK:MD_DefectCause.CauseCode'],
    ['ParetoFlag','BIT',''],
    ['ImageRef','VARCHAR(120)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_DefectCause', ko:'불량 원인 (MD-22)', cols:[
    ['CauseCode','VARCHAR(16)','PK'],
    ['CauseName','NVARCHAR(60)',''],
    ['CauseCategory','VARCHAR(9)',''],
    ['ParentCauseCode','VARCHAR(16)','FK:MD_DefectCause.CauseCode'],
    ['ProcessCode','VARCHAR(10)',''],
    ['RootCauseFlag','BIT',''],
    ['CorrectiveGuide','NVARCHAR(200)',''],
    ['ResponsibleDept','NVARCHAR(30)',''],
    ['SortOrder','INT',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_PackagingSpec', ko:'포장 사양 (MD-23)', cols:[
    ['PackSpecID','VARCHAR(20)','PK'],
    ['ItemID','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['PackType','VARCHAR(12)',''],
    ['QtyPerInner','INT',''],
    ['InnerPerOuter','INT',''],
    ['OuterPerPallet','INT',''],
    ['NetWeightKg','DECIMAL(8,3)',''],
    ['GrossWeightKg','DECIMAL(8,3)',''],
    ['DimLxWxH','VARCHAR(30)',''],
    ['ReturnableFlag','BIT',''],
    ['LabelTemplateID','VARCHAR(20)','FK:MD_LabelTemplate.LabelTemplateID'],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_LabelTemplate', ko:'라벨 템플릿 (MD-24)', cols:[
    ['LabelTemplateID','VARCHAR(20)','PK'],
    ['TemplateName','NVARCHAR(60)',''],
    ['LabelType','VARCHAR(12)',''],
    ['PaperSize','VARCHAR(12)',''],
    ['BarcodeType','VARCHAR(12)',''],
    ['LayoutZPL','NVARCHAR(MAX)',''],
    ['FieldMapJSON','NVARCHAR(MAX)',''],
    ['CustomerID','VARCHAR(20)','FK:MD_Customer.CustomerID'],
    ['Version','INT',''],
    ['PrinterModel','VARCHAR(30)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_ReasonCode', ko:'사유 코드 (MD-25)', cols:[
    ['ReasonCode','VARCHAR(16)','PK'],
    ['ReasonName','NVARCHAR(60)',''],
    ['ReasonType','VARCHAR(12)',''],
    ['AppliesToModule','VARCHAR(10)',''],
    ['RequiresComment','BIT',''],
    ['PlannedFlag','BIT',''],
    ['DisplayOrder','INT',''],
    ['Description','NVARCHAR(120)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_CodeGroup', ko:'공통코드 그룹 (MD-26a)', cols:[
    ['GroupCode','VARCHAR(20)','PK'],
    ['GroupName','NVARCHAR(60)',''],
    ['GroupNameEn','NVARCHAR(60)',''],
    ['Description','NVARCHAR(200)',''],
    ['UseFlag','BIT','']
  ]},
  {name:'MD_CodeItem', ko:'공통코드 항목 (MD-26b)', cols:[
    ['CodeID','VARCHAR(24)','PK'],
    ['GroupCode','VARCHAR(20)','FK:MD_CodeGroup.GroupCode'],
    ['CodeValue','VARCHAR(20)',''],
    ['CodeName','NVARCHAR(60)',''],
    ['CodeNameEn','NVARCHAR(60)',''],
    ['ParentCodeID','VARCHAR(24)','FK:MD_CodeItem.CodeID'],
    ['SortOrder','INT',''],
    ['Attribute1','NVARCHAR(40)',''],
    ['UseFlag','BIT',''],
    ['Description','NVARCHAR(120)','']
  ]},
  {name:'MD_SparePart', ko:'정비 자재 (MD-27)', cols:[
    ['PartNo','VARCHAR(20)','PK'],
    ['PartName','NVARCHAR(60)',''],
    ['Category','VARCHAR(16)',''],
    ['CompatEquipJSON','NVARCHAR(MAX)',''],
    ['UnitCost','DECIMAL(12,2)',''],
    ['UOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['SafetyStock','INT',''],
    ['ReorderPoint','INT',''],
    ['ReorderQty','INT',''],
    ['LeadTimeDays','INT',''],
    ['SupplierID','VARCHAR(20)','FK:MD_Vendor.VendorID'],
    ['StorageLoc','VARCHAR(20)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_PmTemplate', ko:'PM 템플릿 (MD-28a)', cols:[
    ['PMTemplateID','VARCHAR(20)','PK'],
    ['TemplateName','NVARCHAR(60)',''],
    ['EquipType','VARCHAR(16)',''],
    ['CycleBasis','VARCHAR(10)',''],
    ['IntervalValue','INT',''],
    ['IntervalUnit','VARCHAR(8)',''],
    ['StdDurationMin','INT',''],
    ['SafetyLOTOFlag','BIT',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_PmTemplateStep', ko:'PM 점검 항목 (MD-28b)', cols:[
    ['PMStepID','VARCHAR(24)','PK'],
    ['PMTemplateID','VARCHAR(20)','FK:MD_PmTemplate.PMTemplateID'],
    ['StepSeq','INT',''],
    ['StepDescription','NVARCHAR(200)',''],
    ['AcceptanceCriteria','NVARCHAR(200)',''],
    ['RequiredPartNo','VARCHAR(20)','FK:MD_SparePart.PartNo'],
    ['RequiredQty','DECIMAL(10,3)',''],
    ['StepDurationMin','INT','']
  ]},
  {name:'MD_LineTimePattern', ko:'시간패턴 헤더 (MD-29a)', cols:[
    ['PatternID','VARCHAR(20)','PK'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['PatternName','NVARCHAR(50)',''],
    ['DayType','VARCHAR(10)',''],
    ['ShiftModel','VARCHAR(12)',''],
    ['EffectiveFrom','DATE',''],
    ['EffectiveTo','DATE',''],
    ['TotalOperatingMin','INT',''],
    ['TotalPlannedDownMin','INT',''],
    ['TimeZone','VARCHAR(20)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_LineTimeSegment', ko:'시간 세그먼트 (MD-29b)', cols:[
    ['SegmentID','VARCHAR(24)','PK'],
    ['PatternID','VARCHAR(20)','FK:MD_LineTimePattern.PatternID'],
    ['SeqNo','INT',''],
    ['StartMin','SMALLINT',''],
    ['EndMin','SMALLINT',''],
    ['SegmentState','VARCHAR(14)',''],
    ['ReasonCode','VARCHAR(16)','FK:MD_ReasonCode.ReasonCode'],
    ['ShiftCode','VARCHAR(10)',''],
    ['Description','NVARCHAR(60)','']
  ]},
  {name:'MD_Location', ko:'로케이션 (보조)', cols:[
    ['LocationID','VARCHAR(20)','PK'],
    ['LocationName','NVARCHAR(60)',''],
    ['ZoneCode','VARCHAR(10)',''],
    ['Aisle','VARCHAR(5)',''],
    ['Bay','VARCHAR(5)',''],
    ['Slot','VARCHAR(5)',''],
    ['Capacity','DECIMAL(10,3)',''],
    ['LocationType','VARCHAR(20)',''],
    ['PlantID','VARCHAR(10)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_Recipe', ko:'레시피 (보조)', cols:[
    ['RecipeID','VARCHAR(20)','PK'],
    ['RecipeName','NVARCHAR(60)',''],
    ['RecipeType','VARCHAR(15)',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['CycleTime','INT',''],
    ['ParamsJSON','NVARCHAR(MAX)',''],
    ['Version','VARCHAR(10)',''],
    ['EffectiveDate','DATE',''],
    ['Status','VARCHAR(10)','']
  ]}
]},

// ──────────────────────────────────────────────────────────────────────
// WH · Warehouse (8 tables)
// ──────────────────────────────────────────────────────────────────────
WH: { cols: 3, tables: [
  {name:'WH_PurchaseOrder', ko:'구매발주 (SCM)', cols:[
    ['PoID','INT IDENTITY','PK'],
    ['PoNumber','VARCHAR(20)',''],
    ['PoLineNo','INT',''],
    ['VendorID','VARCHAR(20)','FK:MD_Vendor.VendorID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['OrderQty','DECIMAL(12,3)',''],
    ['ReceivedQty','DECIMAL(12,3)',''],
    ['UnitCode','VARCHAR(10)',''],
    ['UnitPrice','DECIMAL(14,4)',''],
    ['Currency','CHAR(3)',''],
    ['OrderDate','DATE',''],
    ['DueDate','DATE',''],
    ['Status','VARCHAR(20)',''],
    ['SapSyncedAt','DATETIME2',''],
    ['CreatedAt','DATETIME2','']
  ]},
  {name:'WH_Receiving', ko:'입고 실적', cols:[
    ['ReceivingID','INT IDENTITY','PK'],
    ['ReceivingNo','VARCHAR(24)',''],
    ['PoID','INT','FK:WH_PurchaseOrder.PoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['VendorID','VARCHAR(20)','FK:MD_Vendor.VendorID'],
    ['ReceivedQty','DECIMAL(12,3)',''],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotCode','VARCHAR(40)',''],
    ['ReceivedAt','DATETIME2',''],
    ['ReceivedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['TerminalID','VARCHAR(20)',''],
    ['QcStatus','VARCHAR(20)',''],
    ['LabelPrinted','BIT','']
  ]},
  {name:'WH_Inventory', ko:'현재고', cols:[
    ['InventoryID','INT IDENTITY','PK'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['OnHandQty','DECIMAL(14,3)',''],
    ['ReservedQty','DECIMAL(14,3)',''],
    ['UnitCost','DECIMAL(14,4)',''],
    ['LastReceivedAt','DATETIME2',''],
    ['ExpiryDate','DATE',''],
    ['Status','VARCHAR(20)','']
  ]},
  {name:'WH_InventorySnapshot', ko:'재고 일일 스냅샷', cols:[
    ['SnapshotID','BIGINT IDENTITY','PK'],
    ['SnapshotDate','DATE',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['OnHandQty','DECIMAL(14,3)',''],
    ['UnitCost','DECIMAL(14,4)',''],
    ['TotalValue','DECIMAL(16,2)','']
  ]},
  {name:'WH_InventoryAdjust', ko:'재고 조정', cols:[
    ['AdjustID','INT IDENTITY','PK'],
    ['AdjustNo','VARCHAR(24)',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['QtyBefore','DECIMAL(14,3)',''],
    ['Delta','DECIMAL(14,3)',''],
    ['QtyAfter','DECIMAL(14,3)',''],
    ['ReasonCode','VARCHAR(30)',''],
    ['ReasonNote','NVARCHAR(500)',''],
    ['Status','VARCHAR(20)',''],
    ['RequestedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApprovedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'WH_ReleaseSchedule', ko:'출고 예정 (WO 수요)', cols:[
    ['ReleaseScheduleID','INT IDENTITY','PK'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['DemandQty','DECIMAL(14,3)',''],
    ['PickedQty','DECIMAL(14,3)',''],
    ['RequiredAt','DATETIME2',''],
    ['Priority','TINYINT',''],
    ['Status','VARCHAR(20)','']
  ]},
  {name:'WH_ReleasePicking', ko:'출고 피킹', cols:[
    ['PickingID','INT IDENTITY','PK'],
    ['PickingNo','VARCHAR(24)',''],
    ['ReleaseScheduleID','INT','FK:WH_ReleaseSchedule.ReleaseScheduleID'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['PickedQty','DECIMAL(14,3)',''],
    ['DestLineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['PickedAt','DATETIME2',''],
    ['PickedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['TerminalID','VARCHAR(20)',''],
    ['FifoOverride','BIT',''],
    ['OverrideReason','NVARCHAR(200)',''],
    ['OverrideApprover','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'WH_TransactionHistory', ko:'입출고 트랜잭션 (append-only)', cols:[
    ['TxnID','BIGINT IDENTITY','PK'],
    ['TxnTime','DATETIME2',''],
    ['TxnType','VARCHAR(10)',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['QtyBefore','DECIMAL(14,3)',''],
    ['Delta','DECIMAL(14,3)',''],
    ['QtyAfter','DECIMAL(14,3)',''],
    ['ReasonCode','VARCHAR(30)',''],
    ['RefDocType','VARCHAR(20)',''],
    ['RefDocID','INT',''],
    ['OperatorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApproverID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['Note','NVARCHAR(500)','']
  ]}
]},

// ──────────────────────────────────────────────────────────────────────
// PP · Production Planning (16 tables)
// ──────────────────────────────────────────────────────────────────────
PP: { cols: 4, tables: [
  {name:'PP_Forecast', ko:'수요예측', cols:[
    ['ForecastID','INT IDENTITY','PK'],
    ['ForecastBatch','VARCHAR(20)',''],
    ['CustomerID','VARCHAR(20)','FK:MD_Customer.CustomerID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['ForecastMonth','DATE',''],
    ['ForecastQty','DECIMAL(14,3)',''],
    ['Confidence','VARCHAR(10)',''],
    ['Source','VARCHAR(20)',''],
    ['ImportedAt','DATETIME2',''],
    ['ImportedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'PP_ForecastHistory', ko:'예측 이력', cols:[
    ['HistoryID','BIGINT IDENTITY','PK'],
    ['ForecastID','INT','FK:PP_Forecast.ForecastID'],
    ['PrevBatch','VARCHAR(20)',''],
    ['PrevQty','DECIMAL(14,3)',''],
    ['NewQty','DECIMAL(14,3)',''],
    ['ChangedAt','DATETIME2',''],
    ['ChangedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'PP_CustomerOrder', ko:'수주 (SO)', cols:[
    ['SoID','INT IDENTITY','PK'],
    ['SoNumber','VARCHAR(20)',''],
    ['SoLineNo','INT',''],
    ['CustomerID','VARCHAR(20)','FK:MD_Customer.CustomerID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['OrderQty','DECIMAL(14,3)',''],
    ['ShippedQty','DECIMAL(14,3)',''],
    ['OrderDate','DATE',''],
    ['RequestedDeliveryDate','DATE',''],
    ['PromisedDate','DATE',''],
    ['Status','VARCHAR(20)',''],
    ['SapSyncedAt','DATETIME2','']
  ]},
  {name:'PP_SupplyPlan', ko:'공급계획 헤더', cols:[
    ['PlanID','INT IDENTITY','PK'],
    ['PlanCode','VARCHAR(20)',''],
    ['PlanPeriod','DATE',''],
    ['Status','VARCHAR(20)',''],
    ['ConfirmedAt','DATETIME2',''],
    ['ConfirmedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['SapImportBatch','VARCHAR(40)','']
  ]},
  {name:'PP_SupplyPlanDetail', ko:'공급계획 상세', cols:[
    ['PlanDetailID','INT IDENTITY','PK'],
    ['PlanID','INT','FK:PP_SupplyPlan.PlanID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['PlannedQty','DECIMAL(14,3)',''],
    ['FgOnHand','DECIMAL(14,3)',''],
    ['NetRequirement','DECIMAL(14,3)',''],
    ['DueDate','DATE','']
  ]},
  {name:'PP_WorkOrder', ko:'★ 작업지시 (WO)', cols:[
    ['WoID','INT IDENTITY','PK'],
    ['WoNumber','VARCHAR(20)',''],
    ['PlanID','INT','FK:PP_SupplyPlan.PlanID'],
    ['SoID','INT','FK:PP_CustomerOrder.SoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['OrderQty','DECIMAL(14,3)',''],
    ['OpenQty','DECIMAL(14,3)',''],
    ['CompletedQty','DECIMAL(14,3)',''],
    ['ScrapQty','DECIMAL(14,3)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['MoldID','VARCHAR(20)','FK:MD_Mold.MoldID'],
    ['RecipeID','VARCHAR(20)','FK:MD_Recipe.RecipeID'],
    ['BomVersion','VARCHAR(10)',''],
    ['BopVersion','VARCHAR(10)',''],
    ['Routing','CHAR(1)',''],
    ['PlannedStart','DATETIME2',''],
    ['PlannedEnd','DATETIME2',''],
    ['ActualStart','DATETIME2',''],
    ['ActualEnd','DATETIME2',''],
    ['DueDate','DATE',''],
    ['Status','VARCHAR(20)',''],
    ['TerminalLock','VARCHAR(20)',''],
    ['Priority','TINYINT',''],
    ['ReleasedAt','DATETIME2',''],
    ['ReleasedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'PP_WorkOrderRouting', ko:'WO 라우팅 (BOP 스냅샷)', cols:[
    ['RoutingLineID','INT IDENTITY','PK'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['StepSeq','TINYINT',''],
    ['ProcessCode','VARCHAR(10)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['StdCycleSec','INT',''],
    ['StdYieldPct','DECIMAL(5,2)',''],
    ['Status','VARCHAR(20)',''],
    ['ActualStart','DATETIME2',''],
    ['ActualEnd','DATETIME2','']
  ]},
  {name:'PP_MaterialReservation', ko:'WO 자재 예약', cols:[
    ['ReservationID','INT IDENTITY','PK'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['RequiredQty','DECIMAL(14,3)',''],
    ['ReservedQty','DECIMAL(14,3)',''],
    ['IssuedQty','DECIMAL(14,3)',''],
    ['RequiredAt','DATETIME2',''],
    ['Status','VARCHAR(20)','']
  ]},
  {name:'PP_PurchaseRequest', ko:'구매요청 (MRP 결과)', cols:[
    ['PrID','INT IDENTITY','PK'],
    ['PrNumber','VARCHAR(20)',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['VendorID','VARCHAR(20)','FK:MD_Vendor.VendorID'],
    ['RequiredQty','DECIMAL(14,3)',''],
    ['RequiredDate','DATE',''],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['Status','VARCHAR(20)',''],
    ['ApprovedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApprovedAt','DATETIME2',''],
    ['SapPoNumber','VARCHAR(20)','']
  ]},
  {name:'PP_PRSendLog', ko:'PR SAP 송신 로그', cols:[
    ['SendLogID','BIGINT IDENTITY','PK'],
    ['PrID','INT','FK:PP_PurchaseRequest.PrID'],
    ['AttemptNo','TINYINT',''],
    ['SentAt','DATETIME2',''],
    ['Endpoint','VARCHAR(200)',''],
    ['RequestPayload','NVARCHAR(MAX)',''],
    ['ResponseCode','INT',''],
    ['ResponsePayload','NVARCHAR(MAX)',''],
    ['Result','VARCHAR(20)','']
  ]},
  {name:'PP_MRPLog', ko:'MRP 실행 로그', cols:[
    ['MrpRunID','INT IDENTITY','PK'],
    ['RunAt','DATETIME2',''],
    ['RunBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['HorizonStart','DATE',''],
    ['HorizonEnd','DATE',''],
    ['WosConsidered','INT',''],
    ['PrsCreated','INT',''],
    ['ShortageCount','INT',''],
    ['DurationMs','INT',''],
    ['Status','VARCHAR(20)','']
  ]},
  {name:'PP_LineSchedule', ko:'라인 스케줄 (LSB)', cols:[
    ['ScheduleID','INT IDENTITY','PK'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['ScheduleDate','DATE',''],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['StartMin','SMALLINT',''],
    ['EndMin','SMALLINT',''],
    ['PlannedQty','DECIMAL(14,3)',''],
    ['PatternID','VARCHAR(20)','FK:MD_LineTimePattern.PatternID'],
    ['Status','VARCHAR(20)',''],
    ['PublishedAt','DATETIME2',''],
    ['PublishedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'PP_LineStateLog', ko:'라인 상태 분단위 (ODM)', cols:[
    ['StateLogID','BIGINT IDENTITY','PK'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['MinuteTS','DATETIME2',''],
    ['State','VARCHAR(20)',''],
    ['PlanState','VARCHAR(20)',''],
    ['RunFlag','BIT',''],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['ClassifiedAt','DATETIME2','']
  ]},
  {name:'PP_LineDowntimeLog', ko:'비가동 사유 (DTL)', cols:[
    ['DowntimeID','INT IDENTITY','PK'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['StartTS','DATETIME2',''],
    ['EndTS','DATETIME2',''],
    ['DurationMin','INT',''],
    ['ReasonCode','VARCHAR(20)',''],
    ['CauseCode','VARCHAR(30)',''],
    ['Comment','NVARCHAR(500)',''],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['LoggedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['AndonID','INT','FK:PR_AndonCall.AndonID']
  ]},
  {name:'PP_LineOEE', ko:'OEE 스냅샷', cols:[
    ['OeeSnapshotID','INT IDENTITY','PK'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['PeriodDate','DATE',''],
    ['ShiftCode','VARCHAR(10)',''],
    ['LoadingMin','INT',''],
    ['PlannedDownMin','INT',''],
    ['UnplannedDownMin','INT',''],
    ['OperatingMin','INT',''],
    ['TotalProducedQty','DECIMAL(14,3)',''],
    ['GoodQty','DECIMAL(14,3)',''],
    ['Availability','DECIMAL(5,4)',''],
    ['Performance','DECIMAL(5,4)',''],
    ['Quality','DECIMAL(5,4)',''],
    ['OEE','DECIMAL(5,4)','']
  ]},
  {name:'PP_ProductionCalendarOverride', ko:'캘린더 변경', cols:[
    ['OverrideID','INT IDENTITY','PK'],
    ['OverrideDate','DATE',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['DayType','VARCHAR(20)',''],
    ['PatternID','VARCHAR(20)','FK:MD_LineTimePattern.PatternID'],
    ['CapacityFactor','DECIMAL(5,2)',''],
    ['Reason','NVARCHAR(200)',''],
    ['ApprovedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApprovedAt','DATETIME2','']
  ]}
]},

// ──────────────────────────────────────────────────────────────────────
// PR · Production Shared (23 tables, includes tbl_Lot)
// ──────────────────────────────────────────────────────────────────────
PR: { cols: 4, tables: [
  {name:'tbl_Lot', ko:'★ LOT 마스터 (전 모듈 앵커)', cols:[
    ['LotID','INT IDENTITY','PK'],
    ['LotCode','VARCHAR(40)',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['ProcessCode','VARCHAR(10)',''],
    ['BatchSize','DECIMAL(14,3)',''],
    ['RemainingQty','DECIMAL(14,3)',''],
    ['ParentLotID','INT','FK:tbl_Lot.LotID'],
    ['ProducedAt','DATETIME2',''],
    ['Status','VARCHAR(20)',''],
    ['QualityFlag','VARCHAR(10)',''],
    ['CurrentLocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['ExpiryDate','DATE','']
  ]},
  {name:'PR_PopSession', ko:'POP 로그인 세션', cols:[
    ['SessionID','INT IDENTITY','PK'],
    ['OperatorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['TerminalID','VARCHAR(20)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['ShiftCode','VARCHAR(10)',''],
    ['AuthMethod','VARCHAR(20)',''],
    ['StartedAt','DATETIME2',''],
    ['ExpiresAt','DATETIME2',''],
    ['LoggedOutAt','DATETIME2',''],
    ['LogoutReason','VARCHAR(20)','']
  ]},
  {name:'PR_PopAuthLog', ko:'POP 인증 감사', cols:[
    ['AuthLogID','BIGINT IDENTITY','PK'],
    ['TerminalID','VARCHAR(20)',''],
    ['AttemptedID','VARCHAR(50)',''],
    ['AuthMethod','VARCHAR(20)',''],
    ['Result','VARCHAR(10)',''],
    ['FailReason','VARCHAR(40)',''],
    ['AttemptedAt','DATETIME2','']
  ]},
  {name:'PR_WoAcceptance', ko:'WO 수락 (INJ-03)', cols:[
    ['AcceptID','INT IDENTITY','PK'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['TerminalID','VARCHAR(20)',''],
    ['OperatorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['AcceptedAt','DATETIME2',''],
    ['CheckResults','NVARCHAR(MAX)',''],
    ['CheckPassed','BIT','']
  ]},
  {name:'PR_ProductionResult', ko:'★ 생산실적 (사이클별)', cols:[
    ['ResultID','INT IDENTITY','PK'],
    ['EntryNo','VARCHAR(28)',''],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['ProcessCode','VARCHAR(10)',''],
    ['GoodQty','INT',''],
    ['CycleSec','INT',''],
    ['MoldID','VARCHAR(20)','FK:MD_Mold.MoldID'],
    ['FabricRollID','INT','FK:tbl_Lot.LotID'],
    ['FabricConsumedM','DECIMAL(8,3)',''],
    ['BondTempAvg','DECIMAL(5,1)',''],
    ['OperatorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['SessionID','INT','FK:PR_PopSession.SessionID'],
    ['DefectFlag','BIT',''],
    ['ReviewFlag','BIT',''],
    ['EntryAt','DATETIME2','']
  ]},
  {name:'PR_DefectDetail', ko:'불량 상세', cols:[
    ['DefectID','INT IDENTITY','PK'],
    ['ResultID','INT','FK:PR_ProductionResult.ResultID'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['ProcessCode','VARCHAR(10)',''],
    ['DefectCode','VARCHAR(16)','FK:MD_DefectCode.DefectCode'],
    ['Qty','INT',''],
    ['SeqNos','NVARCHAR(MAX)',''],
    ['ReasonNote','NVARCHAR(500)',''],
    ['PhotoUrl','VARCHAR(300)',''],
    ['CorrectiveAction','NVARCHAR(500)',''],
    ['Disposition','VARCHAR(20)',''],
    ['DetectedAt','DATETIME2',''],
    ['RegisteredBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'PR_DefectAutoLink', ko:'불량 자동 원인', cols:[
    ['LinkID','INT IDENTITY','PK'],
    ['DefectID','INT','FK:PR_DefectDetail.DefectID'],
    ['LinkType','VARCHAR(30)',''],
    ['RefDocType','VARCHAR(20)',''],
    ['RefDocID','INT',''],
    ['ConfidenceScore','DECIMAL(4,3)',''],
    ['LinkedAt','DATETIME2','']
  ]},
  {name:'PR_CycleAnomalyLog', ko:'CT 이탈 로그', cols:[
    ['AnomalyID','INT IDENTITY','PK'],
    ['ResultID','INT','FK:PR_ProductionResult.ResultID'],
    ['ExpectedCt','INT',''],
    ['ActualCt','INT',''],
    ['DeviationPct','DECIMAL(6,2)',''],
    ['DetectedAt','DATETIME2','']
  ]},
  {name:'PR_MoldChange', ko:'금형 교체 (INJ-06)', cols:[
    ['MoldChangeID','INT IDENTITY','PK'],
    ['EquipID','VARCHAR(20)','FK:MD_Equipment.EquipID'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['OldMoldID','VARCHAR(20)','FK:MD_Mold.MoldID'],
    ['NewMoldID','VARCHAR(20)','FK:MD_Mold.MoldID'],
    ['OldMoldFinalShots','INT',''],
    ['NewMoldStartShots','INT',''],
    ['Reason','VARCHAR(20)',''],
    ['MntWoID','INT','FK:MNT_WorkOrder.WorkOrderID'],
    ['DowntimeMin','INT',''],
    ['StartedAt','DATETIME2',''],
    ['CompletedAt','DATETIME2',''],
    ['ChangedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'PR_ShotCount', ko:'금형 쇼트 이력', cols:[
    ['ShotCountID','BIGINT IDENTITY','PK'],
    ['MoldID','VARCHAR(20)','FK:MD_Mold.MoldID'],
    ['RecordDate','DATE',''],
    ['ShiftCode','VARCHAR(10)',''],
    ['ShotsAdded','INT',''],
    ['CumulativeShots','INT',''],
    ['RatedShots','INT',''],
    ['RecordedAt','DATETIME2','']
  ]},
  {name:'PR_EquipStatusLog', ko:'설비 상태 로그 (PLC)', cols:[
    ['EquipStatusLogID','BIGINT IDENTITY','PK'],
    ['EquipID','VARCHAR(20)','FK:MD_Equipment.EquipID'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['Status','VARCHAR(20)',''],
    ['ReasonCode','VARCHAR(30)',''],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['StartedAt','DATETIME2',''],
    ['DurationSec','INT','']
  ]},
  {name:'PR_AndonCall', ko:'★ 안돈 호출 (5년)', cols:[
    ['AndonID','INT IDENTITY','PK'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['EquipID','VARCHAR(20)','FK:MD_Equipment.EquipID'],
    ['TriggerSource','VARCHAR(20)',''],
    ['RuleID','VARCHAR(20)',''],
    ['Severity','VARCHAR(10)',''],
    ['TriggeredAt','DATETIME2',''],
    ['AckedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['AckedAt','DATETIME2',''],
    ['ReasonCode','VARCHAR(30)',''],
    ['CorrectiveAction','NVARCHAR(500)',''],
    ['ResumedAt','DATETIME2',''],
    ['DowntimeSec','INT',''],
    ['Status','VARCHAR(20)','']
  ]},
  {name:'PR_AndonPush', ko:'안돈 송신 로그', cols:[
    ['PushID','BIGINT IDENTITY','PK'],
    ['AndonID','INT','FK:PR_AndonCall.AndonID'],
    ['Recipient','VARCHAR(100)',''],
    ['Channel','VARCHAR(20)',''],
    ['SentAt','DATETIME2',''],
    ['DeliveredAt','DATETIME2',''],
    ['Result','VARCHAR(20)','']
  ]},
  {name:'PR_PlcInterlock', ko:'PLC 인터록', cols:[
    ['InterlockID','INT IDENTITY','PK'],
    ['EquipID','VARCHAR(20)','FK:MD_Equipment.EquipID'],
    ['LockedAt','DATETIME2',''],
    ['UnlockedAt','DATETIME2',''],
    ['LockReason','VARCHAR(40)',''],
    ['AndonID','INT','FK:PR_AndonCall.AndonID']
  ]},
  {name:'PR_ShiftHandover', ko:'교대 인수인계', cols:[
    ['HandoverID','INT IDENTITY','PK'],
    ['HandoverDate','DATE',''],
    ['ShiftCode','VARCHAR(10)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['ProcessCode','VARCHAR(10)',''],
    ['SummaryJson','NVARCHAR(MAX)',''],
    ['PdfUrl','VARCHAR(300)',''],
    ['SignedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ReceivedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['SignedAt','DATETIME2','']
  ]},
  {name:'PR_DashTileCache', ko:'POP 대시 캐시', cols:[
    ['LineID','VARCHAR(20)','PK'],
    ['TileID','VARCHAR(30)','PK'],
    ['Value','NVARCHAR(200)',''],
    ['UpdatedAt','DATETIME2',''],
    ['TtlSec','INT','']
  ]},
  {name:'PR_DefectRateCache', ko:'불량률 캐시', cols:[
    ['WoID','INT','PK'],
    ['TotalGood','INT',''],
    ['TotalDefect','INT',''],
    ['RatePct','DECIMAL(6,3)',''],
    ['UpdatedAt','DATETIME2','']
  ]},
  {name:'PR_FabricIssue', ko:'IMG 원단 투입', cols:[
    ['FabricIssueID','INT IDENTITY','PK'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['FabricRollLotID','INT','FK:tbl_Lot.LotID'],
    ['ColorCode','VARCHAR(10)',''],
    ['MountedAt','DATETIME2',''],
    ['DismountedAt','DATETIME2',''],
    ['InitialRemainingM','DECIMAL(8,3)',''],
    ['FinalRemainingM','DECIMAL(8,3)',''],
    ['OperatorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['SessionID','INT','FK:PR_PopSession.SessionID'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID']
  ]},
  {name:'PR_FabricIssueAttempt', ko:'원단 시도 감사', cols:[
    ['AttemptID','BIGINT IDENTITY','PK'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['ScannedRollLotID','INT','FK:tbl_Lot.LotID'],
    ['ScannedColor','VARCHAR(10)',''],
    ['ExpectedColor','VARCHAR(10)',''],
    ['Result','VARCHAR(10)',''],
    ['AttemptedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['AttemptedAt','DATETIME2','']
  ]},
  {name:'PR_FabricDeductionLog', ko:'원단 차감 (7년)', cols:[
    ['DeductionID','BIGINT IDENTITY','PK'],
    ['FabricRollLotID','INT','FK:tbl_Lot.LotID'],
    ['ResultID','INT','FK:PR_ProductionResult.ResultID'],
    ['ConsumedM','DECIMAL(8,3)',''],
    ['BeforeM','DECIMAL(8,3)',''],
    ['AfterM','DECIMAL(8,3)',''],
    ['DeductedAt','DATETIME2','']
  ]},
  {name:'PR_BondSetup', ko:'IMG 본드 설정', cols:[
    ['BondSetupID','INT IDENTITY','PK'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['RecipeID','VARCHAR(20)','FK:MD_Recipe.RecipeID'],
    ['PressureSp','DECIMAL(6,2)',''],
    ['TempSp','DECIMAL(5,1)',''],
    ['HoldSecSp','INT',''],
    ['TensionSp','DECIMAL(6,2)',''],
    ['LoadedAt','DATETIME2',''],
    ['LoadedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['Status','VARCHAR(20)','']
  ]},
  {name:'PR_BondCycleLog', ko:'본드 사이클 PLC', cols:[
    ['BondCycleID','BIGINT IDENTITY','PK'],
    ['ResultID','INT','FK:PR_ProductionResult.ResultID'],
    ['BondSetupID','INT','FK:PR_BondSetup.BondSetupID'],
    ['PressureAvg','DECIMAL(6,2)',''],
    ['TempAvg','DECIMAL(5,1)',''],
    ['HoldActualSec','INT',''],
    ['TensionAvg','DECIMAL(6,2)',''],
    ['WithinSpec','BIT',''],
    ['SampledAt','DATETIME2','']
  ]},
  {name:'PR_BondSetupAudit', ko:'본드 변경 감사 (7년)', cols:[
    ['AuditID','BIGINT IDENTITY','PK'],
    ['BondSetupID','INT','FK:PR_BondSetup.BondSetupID'],
    ['FieldName','VARCHAR(40)',''],
    ['OldValue','NVARCHAR(100)',''],
    ['NewValue','NVARCHAR(100)',''],
    ['ReasonCode','VARCHAR(30)',''],
    ['ChangedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApprovedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ChangedAt','DATETIME2','']
  ]}
]},

// ──────────────────────────────────────────────────────────────────────
// PNT · Painting (22 tables, RFID-tracked)
// ──────────────────────────────────────────────────────────────────────
PNT: { cols: 4, tables: [
  {name:'PNT_DailyPlan', ko:'일일 계획 (PNT-01)', cols:[
    ['PlanID','INT IDENTITY','PK'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['PlanDate','DATE',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['RalColor','VARCHAR(12)','FK:MD_RalColor.RALCode'],
    ['TargetQty','INT',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['OvenID','VARCHAR(20)','FK:MD_Oven.OvenID'],
    ['StartTime','TIME',''],
    ['JigsRequired','INT',''],
    ['LotsRequired','INT',''],
    ['ReadyFlag','BIT','']
  ]},
  {name:'PNT_VirtualLot', ko:'★ 가상 LOT (PNT-02)', cols:[
    ['VirtualLotID','INT IDENTITY','PK'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['PlanID','INT','FK:PNT_DailyPlan.PlanID'],
    ['JigID','VARCHAR(20)','FK:MD_Jig.JigID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['RalColor','VARCHAR(12)','FK:MD_RalColor.RALCode'],
    ['TargetQty','INT',''],
    ['LoadedQty','INT',''],
    ['ConfirmedQty','INT',''],
    ['DefectQty','INT',''],
    ['Status','VARCHAR(20)',''],
    ['EnhancedInspection','BIT',''],
    ['IssuedAt','DATETIME2',''],
    ['IssuedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['BindAt','DATETIME2',''],
    ['BindReason','VARCHAR(40)','']
  ]},
  {name:'PNT_JigBindingLog', ko:'지그 바인딩 이력', cols:[
    ['BindingLogID','INT IDENTITY','PK'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['JigID','VARCHAR(20)','FK:MD_Jig.JigID'],
    ['BoundAt','DATETIME2',''],
    ['UnboundAt','DATETIME2',''],
    ['Reason','VARCHAR(40)',''],
    ['ActorID','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'PNT_SeqAllocator', ko:'LotID 채번 락', cols:[
    ['PlanDate','DATE','PK'],
    ['LineID','VARCHAR(20)','PK'],
    ['NextSeq','INT',''],
    ['UpdatedAt','DATETIME2','']
  ]},
  {name:'PNT_JigLoad', ko:'지그 로딩 (PNT-03)', cols:[
    ['LoadID','INT IDENTITY','PK'],
    ['JigID','VARCHAR(20)','FK:MD_Jig.JigID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['LoadedQty','INT',''],
    ['OperatorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['PdaScanAt','DATETIME2',''],
    ['R1ReadAt','DATETIME2',''],
    ['MatchStatus','VARCHAR(20)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID']
  ]},
  {name:'PNT_LineEvent', ko:'★ RFID 통과 (R1/R2/R3, 5년)', cols:[
    ['EventID','BIGINT IDENTITY','PK'],
    ['TagID','VARCHAR(24)','FK:MD_RfidTag.TagID'],
    ['JigID','VARCHAR(20)','FK:MD_Jig.JigID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['ReaderID','VARCHAR(20)','FK:MD_RfidReader.ReaderID'],
    ['AntennaPort','TINYINT',''],
    ['TagRole','VARCHAR(10)',''],
    ['EventTS','DATETIME2',''],
    ['Rssi','SMALLINT',''],
    ['ReadCount','INT',''],
    ['TriggerType','VARCHAR(20)','']
  ]},
  {name:'PNT_TagFailureLog', ko:'태그 실패 로그', cols:[
    ['FailureID','INT IDENTITY','PK'],
    ['TagID','VARCHAR(24)','FK:MD_RfidTag.TagID'],
    ['ReaderID','VARCHAR(20)','FK:MD_RfidReader.ReaderID'],
    ['FailedAt','DATETIME2',''],
    ['FailType','VARCHAR(20)',''],
    ['FallbackAction','VARCHAR(30)',''],
    ['ResolvedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'PNT_OvenLog', ko:'오븐 체류 (PNT-05)', cols:[
    ['OvenLogID','INT IDENTITY','PK'],
    ['OvenID','VARCHAR(20)','FK:MD_Oven.OvenID'],
    ['JigID','VARCHAR(20)','FK:MD_Jig.JigID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['EntryTS','DATETIME2',''],
    ['ExitTS','DATETIME2',''],
    ['DwellSec','INT',''],
    ['TempCurve','NVARCHAR(MAX)',''],
    ['MinTemp','DECIMAL(5,1)',''],
    ['MaxTemp','DECIMAL(5,1)',''],
    ['AvgTemp','DECIMAL(5,1)',''],
    ['WithinSpec','BIT','']
  ]},
  {name:'PNT_OvenTempSample', ko:'오븐 5초 샘플 (5년)', cols:[
    ['SampleID','BIGINT IDENTITY','PK'],
    ['OvenID','VARCHAR(20)','FK:MD_Oven.OvenID'],
    ['ZoneID','TINYINT',''],
    ['TempC','DECIMAL(5,1)',''],
    ['SampledAt','DATETIME2','']
  ]},
  {name:'PNT_OvenDeviationLog', ko:'오븐 온도 이탈', cols:[
    ['DeviationID','INT IDENTITY','PK'],
    ['OvenID','VARCHAR(20)','FK:MD_Oven.OvenID'],
    ['StartTS','DATETIME2',''],
    ['EndTS','DATETIME2',''],
    ['MaxDelta','DECIMAL(5,1)',''],
    ['AffectedLots','NVARCHAR(MAX)',''],
    ['MntWoID','INT','FK:MNT_WorkOrder.WorkOrderID'],
    ['AndonID','INT','FK:PR_AndonCall.AndonID']
  ]},
  {name:'PNT_OvenSpikeLog', ko:'오븐 단일 스파이크', cols:[
    ['SpikeID','INT IDENTITY','PK'],
    ['OvenID','VARCHAR(20)','FK:MD_Oven.OvenID'],
    ['DetectedAt','DATETIME2',''],
    ['TempC','DECIMAL(5,1)',''],
    ['Delta','DECIMAL(5,1)','']
  ]},
  {name:'PNT_JigUnload', ko:'지그 언로딩 (PNT-06)', cols:[
    ['UnloadID','INT IDENTITY','PK'],
    ['JigID','VARCHAR(20)','FK:MD_Jig.JigID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['ConfirmedQty','INT',''],
    ['ExpectedQty','INT',''],
    ['ShortReason','VARCHAR(30)',''],
    ['OperatorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['R3ReadAt','DATETIME2',''],
    ['ConfirmedAt','DATETIME2','']
  ]},
  {name:'PNT_PartLossLog', ko:'부품 손실 로그', cols:[
    ['LossID','INT IDENTITY','PK'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['LossQty','INT',''],
    ['ReasonCode','VARCHAR(30)',''],
    ['ReasonNote','NVARCHAR(300)',''],
    ['LoggedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['LoggedAt','DATETIME2','']
  ]},
  {name:'PNT_StationStatsCache', ko:'라인보드 캐시', cols:[
    ['StationID','VARCHAR(20)','PK'],
    ['ActiveCount','INT',''],
    ['AvgDwellSec','INT',''],
    ['BottleneckFlag','BIT',''],
    ['UpdatedAt','DATETIME2','']
  ]},
  {name:'PNT_LotLabel', ko:'LOT 라벨 (PNT-07)', cols:[
    ['LabelID','INT IDENTITY','PK'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['SeqNo','INT',''],
    ['TotalQty','INT',''],
    ['PrintedAt','DATETIME2',''],
    ['PrintedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['AppliedAt','DATETIME2',''],
    ['AppliedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['Status','VARCHAR(20)','']
  ]},
  {name:'PNT_LabelPrintJob', ko:'라벨 프린트 잡', cols:[
    ['JobID','INT IDENTITY','PK'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['PrinterID','VARCHAR(20)',''],
    ['Zpl','NVARCHAR(MAX)',''],
    ['SubmittedAt','DATETIME2',''],
    ['CompletedAt','DATETIME2',''],
    ['Status','VARCHAR(20)',''],
    ['FailReason','VARCHAR(200)','']
  ]},
  {name:'PNT_LabelScanLog', ko:'라벨 스캔 이력', cols:[
    ['ScanID','BIGINT IDENTITY','PK'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['LabelID','INT','FK:PNT_LotLabel.LabelID'],
    ['ScannedSeq','INT',''],
    ['Position','VARCHAR(10)',''],
    ['ScannedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ScannedAt','DATETIME2','']
  ]},
  {name:'PNT_ShiftReport', ko:'교대 보고서 헤더', cols:[
    ['ReportID','INT IDENTITY','PK'],
    ['ShiftDate','DATE',''],
    ['ShiftType','VARCHAR(10)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['LoadedQty','INT',''],
    ['ConfirmedQty','INT',''],
    ['DefectQty','INT',''],
    ['OvenDeviations','INT',''],
    ['Fallbacks','INT',''],
    ['SpareTagsUsed','INT',''],
    ['JigSwaps','INT',''],
    ['YieldPct','DECIMAL(5,2)',''],
    ['CompiledAt','DATETIME2',''],
    ['SignedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['SignedAt','DATETIME2',''],
    ['PdfUrl','VARCHAR(300)',''],
    ['Version','TINYINT','']
  ]},
  {name:'PNT_ShiftReportLineItem', ko:'교대 WO 명세', cols:[
    ['LineItemID','INT IDENTITY','PK'],
    ['ReportID','INT','FK:PNT_ShiftReport.ReportID'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['RalColor','VARCHAR(12)','FK:MD_RalColor.RALCode'],
    ['PlanQty','INT',''],
    ['LoadedQty','INT',''],
    ['ConfirmedQty','INT',''],
    ['DefectQty','INT',''],
    ['YieldPct','DECIMAL(5,2)','']
  ]},
  {name:'PNT_ShiftReportAudit', ko:'교대 수정 감사 (7년)', cols:[
    ['AuditID','INT IDENTITY','PK'],
    ['ReportID','INT','FK:PNT_ShiftReport.ReportID'],
    ['ChangedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ChangedAt','DATETIME2',''],
    ['FieldName','VARCHAR(40)',''],
    ['OldValue','NVARCHAR(200)',''],
    ['NewValue','NVARCHAR(200)',''],
    ['Reason','NVARCHAR(300)','']
  ]},
  {name:'PNT_DailyReport', ko:'일일 합산 보고서', cols:[
    ['DailyID','INT IDENTITY','PK'],
    ['ReportDate','DATE',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['TotalConfirmed','INT',''],
    ['TotalDefect','INT',''],
    ['DailyYieldPct','DECIMAL(5,2)',''],
    ['TwoShiftRollupJson','NVARCHAR(MAX)',''],
    ['GeneratedAt','DATETIME2','']
  ]},
  {name:'PNT_QcQueue', ko:'QC 인계 대기열', cols:[
    ['QueueID','INT IDENTITY','PK'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['EnqueuedAt','DATETIME2',''],
    ['EnhancedFlag','BIT',''],
    ['SlaDueAt','DATETIME2',''],
    ['Status','VARCHAR(20)','']
  ]}
]},

// ──────────────────────────────────────────────────────────────────────
// QC · Quality Control (10 tables)
// ──────────────────────────────────────────────────────────────────────
QC: { cols: 3, tables: [
  {name:'QC_Inspection', ko:'★ 검사 (IQC/IPQC/FQC)', cols:[
    ['InspectionID','INT IDENTITY','PK'],
    ['InspectionNo','VARCHAR(24)',''],
    ['InspectionType','VARCHAR(15)',''],
    ['PoID','INT','FK:WH_PurchaseOrder.PoID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['StdID','INT','FK:QC_InspectionStd.StdID'],
    ['CustomerCode','VARCHAR(20)',''],
    ['Mode','VARCHAR(15)',''],
    ['EnhanceReason','VARCHAR(60)',''],
    ['SampleSize','INT',''],
    ['BatchQty','DECIMAL(12,3)',''],
    ['CumulativeGood','INT',''],
    ['DefectQtyTotal','INT',''],
    ['Verdict','VARCHAR(15)',''],
    ['CriticalFlag','BIT',''],
    ['CorrectiveAction','NVARCHAR(500)',''],
    ['ResultJSON','NVARCHAR(MAX)',''],
    ['NcrID','INT','FK:QC_NCR.NcrID'],
    ['HoldID','INT','FK:QC_Hold.HoldID'],
    ['InspectorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApproverID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ResumeBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['InsStartTS','DATETIME2',''],
    ['InsEndTS','DATETIME2','']
  ]},
  {name:'QC_InspectionItem', ko:'검사 항목별 측정값', cols:[
    ['InspectionItemID','INT IDENTITY','PK'],
    ['InspectionID','INT','FK:QC_Inspection.InspectionID'],
    ['ItemSeq','INT',''],
    ['ItemName','NVARCHAR(100)',''],
    ['Standard','NVARCHAR(100)',''],
    ['Measured','NVARCHAR(100)',''],
    ['Result','VARCHAR(10)',''],
    ['PhotoURL','VARCHAR(255)','']
  ]},
  {name:'QC_InspectionStd', ko:'검사 기준서 (버전)', cols:[
    ['StdID','INT IDENTITY','PK'],
    ['StdCode','VARCHAR(30)',''],
    ['VerNo','VARCHAR(8)',''],
    ['StdName','NVARCHAR(120)',''],
    ['InsType','VARCHAR(15)',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['CustomerCode','VARCHAR(20)',''],
    ['Mode','VARCHAR(15)',''],
    ['AQLLevel','DECIMAL(3,2)',''],
    ['SampleInterval','INT',''],
    ['InspItemsJSON','NVARCHAR(MAX)',''],
    ['KPITargetsJSON','NVARCHAR(MAX)',''],
    ['Status','VARCHAR(15)',''],
    ['EffectiveDate','DATE',''],
    ['DraftedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApprovedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['CapaLinkID','INT','FK:QC_CAPA.CapaID']
  ]},
  {name:'QC_NCR', ko:'★ 부적합 보고서', cols:[
    ['NcrID','INT IDENTITY','PK'],
    ['NcrNumber','VARCHAR(24)',''],
    ['SourceType','VARCHAR(20)',''],
    ['SourceID','VARCHAR(24)',''],
    ['InspectionID','INT','FK:QC_Inspection.InspectionID'],
    ['Severity','VARCHAR(10)',''],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['AffectedQty','DECIMAL(12,3)',''],
    ['CustomerCode','VARCHAR(20)',''],
    ['DefectsJSON','NVARCHAR(MAX)',''],
    ['Cause4M','VARCHAR(15)',''],
    ['Disposition','VARCHAR(15)',''],
    ['HoldID','INT','FK:QC_Hold.HoldID'],
    ['CapaID','INT','FK:QC_CAPA.CapaID'],
    ['Status','VARCHAR(15)',''],
    ['ReportedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ReportedAt','DATETIME2',''],
    ['ApprovedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ClosedAt','DATETIME2','']
  ]},
  {name:'QC_NCR_Action', ko:'NCR 처리 이력', cols:[
    ['ActionID','INT IDENTITY','PK'],
    ['NcrID','INT','FK:QC_NCR.NcrID'],
    ['ActionType','VARCHAR(20)',''],
    ['ActionRefID','VARCHAR(24)',''],
    ['ActionNote','NVARCHAR(500)',''],
    ['ActionTS','DATETIME2',''],
    ['ActionBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'QC_Hold', ko:'보류/격리', cols:[
    ['HoldID','INT IDENTITY','PK'],
    ['HoldNumber','VARCHAR(24)',''],
    ['SourceNcrID','INT','FK:QC_NCR.NcrID'],
    ['Severity','VARCHAR(10)',''],
    ['AffectedType','VARCHAR(15)',''],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['FgStockID','INT','FK:FG_Stock.StockID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['HeldQty','DECIMAL(12,3)',''],
    ['PhysicalLocation','VARCHAR(20)',''],
    ['LabelPrintedTS','DATETIME2',''],
    ['Status','VARCHAR(15)',''],
    ['HeldBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['HeldAt','DATETIME2','']
  ]},
  {name:'QC_HoldRelease', ko:'보류 해제 이력', cols:[
    ['ReleaseID','INT IDENTITY','PK'],
    ['HoldID','INT','FK:QC_Hold.HoldID'],
    ['EventType','VARCHAR(15)',''],
    ['ReleaseAction','VARCHAR(15)',''],
    ['ReleaseReason','NVARCHAR(500)',''],
    ['PlantMgrApprovalID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ActorPINHash','VARCHAR(255)',''],
    ['ReleasedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ReleasedAt','DATETIME2',''],
    ['Note','NVARCHAR(500)','']
  ]},
  {name:'QC_CAPA', ko:'★ 시정·예방 조치', cols:[
    ['CapaID','INT IDENTITY','PK'],
    ['CapaNumber','VARCHAR(24)',''],
    ['Type','VARCHAR(15)',''],
    ['TriggerType','VARCHAR(20)',''],
    ['LinkedNcrIDs','NVARCHAR(MAX)',''],
    ['Phase','VARCHAR(10)',''],
    ['Status','VARCHAR(25)',''],
    ['FiveWhyJSON','NVARCHAR(MAX)',''],
    ['RootCause','NVARCHAR(1000)',''],
    ['Cause4M','VARCHAR(15)',''],
    ['ActionsJSON','NVARCHAR(MAX)',''],
    ['EffectivenessJSON','NVARCHAR(MAX)',''],
    ['OwnerID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['QcManagerID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['CustomerImpact','VARCHAR(10)',''],
    ['CustomerNotified','BIT',''],
    ['OpenedAt','DATETIME2',''],
    ['DueDate','DATE',''],
    ['ClosedAt','DATETIME2','']
  ]},
  {name:'QC_CAPA_Action', ko:'CAPA 단계 이력', cols:[
    ['CapaActionID','INT IDENTITY','PK'],
    ['CapaID','INT','FK:QC_CAPA.CapaID'],
    ['ActionType','VARCHAR(20)',''],
    ['CheckDay','INT',''],
    ['Description','NVARCHAR(500)',''],
    ['Metric','NVARCHAR(60)',''],
    ['TargetValue','NVARCHAR(60)',''],
    ['ActualValue','NVARCHAR(60)',''],
    ['Verdict','VARCHAR(10)',''],
    ['OwnerID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['DueDate','DATE',''],
    ['CompletedAt','DATETIME2',''],
    ['EvidenceURL','VARCHAR(255)','']
  ]},
  {name:'QC_Disposition', ko:'처분 결정', cols:[
    ['DispositionID','INT IDENTITY','PK'],
    ['NcrID','INT','FK:QC_NCR.NcrID'],
    ['HoldID','INT','FK:QC_Hold.HoldID'],
    ['DispositionAction','VARCHAR(15)',''],
    ['DispositionQty','DECIMAL(12,3)',''],
    ['Reason','NVARCHAR(500)',''],
    ['CustomerApprovalURL','VARCHAR(255)',''],
    ['DownstreamRefType','VARCHAR(15)',''],
    ['DownstreamRefID','VARCHAR(24)',''],
    ['ApprovedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApprovedAt','DATETIME2','']
  ]}
]},

// ──────────────────────────────────────────────────────────────────────
// FG · Finished Goods (10 tables)
// ──────────────────────────────────────────────────────────────────────
FG: { cols: 3, tables: [
  {name:'FG_Stock', ko:'★ 완제품 재고', cols:[
    ['StockID','INT IDENTITY','PK'],
    ['StockNumber','VARCHAR(24)',''],
    ['FgTriggerID','INT',''],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['CustomerCode','VARCHAR(20)',''],
    ['Qty','DECIMAL(12,3)',''],
    ['Location','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['Status','VARCHAR(15)',''],
    ['HoldFlag','BIT',''],
    ['HoldID','INT','FK:QC_Hold.HoldID'],
    ['ReservationID','INT',''],
    ['StockTS','DATETIME2','']
  ]},
  {name:'FG_PutAway', ko:'완제품 적치 (FG-01)', cols:[
    ['PutAwayID','INT IDENTITY','PK'],
    ['StockID','INT','FK:FG_Stock.StockID'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['Qty','DECIMAL(12,3)',''],
    ['SuggestedLoc','VARCHAR(20)',''],
    ['ActualLoc','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LocOverrideReason','VARCHAR(60)',''],
    ['PalletCount','INT',''],
    ['PalletQty','INT',''],
    ['LabelPrintedTS','DATETIME2',''],
    ['OperatorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['Status','VARCHAR(15)','']
  ]},
  {name:'FG_ShipmentOrder', ko:'★ 출하 지시 헤더', cols:[
    ['ShipmentOrderID','INT IDENTITY','PK'],
    ['ShipOrderNumber','VARCHAR(24)',''],
    ['CustomerCode','VARCHAR(20)',''],
    ['CustomerPO','VARCHAR(40)',''],
    ['Source','VARCHAR(10)',''],
    ['ShipDate','DATE',''],
    ['CarrierCode','VARCHAR(20)',''],
    ['DestPlant','VARCHAR(30)',''],
    ['DestDock','VARCHAR(30)',''],
    ['ReceiverName','VARCHAR(50)',''],
    ['ReceiverPhone','VARCHAR(30)',''],
    ['Status','VARCHAR(15)',''],
    ['PickslipID','VARCHAR(24)',''],
    ['OTDFlag','VARCHAR(10)',''],
    ['ConfirmedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ConfirmedAt','DATETIME2','']
  ]},
  {name:'FG_ShipmentOrderLine', ko:'출하 라인 (SO×LOT)', cols:[
    ['ShipmentOrderLineID','INT IDENTITY','PK'],
    ['ShipmentOrderID','INT','FK:FG_ShipmentOrder.ShipmentOrderID'],
    ['LineSeq','INT',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['OrderedQty','DECIMAL(12,3)',''],
    ['AllocatedQty','DECIMAL(12,3)',''],
    ['StockID','INT','FK:FG_Stock.StockID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['Location','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['ReservationStatus','VARCHAR(15)',''],
    ['ReservedAt','DATETIME2',''],
    ['ReleasedAt','DATETIME2','']
  ]},
  {name:'FG_PickingFifo', ko:'FIFO 피킹 세션', cols:[
    ['PickID','INT IDENTITY','PK'],
    ['PickNumber','VARCHAR(24)',''],
    ['PickslipID','VARCHAR(24)',''],
    ['ShipmentOrderID','INT','FK:FG_ShipmentOrder.ShipmentOrderID'],
    ['PickerID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['StartTS','DATETIME2',''],
    ['EndTS','DATETIME2',''],
    ['PicksJSON','NVARCHAR(MAX)',''],
    ['FifoViolations','INT',''],
    ['OverrideCount','INT',''],
    ['OverrideApprovedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['PartialPicksJSON','NVARCHAR(MAX)',''],
    ['PickedQty','DECIMAL(12,3)',''],
    ['OrderedQty','DECIMAL(12,3)',''],
    ['Status','VARCHAR(15)','']
  ]},
  {name:'FG_LoadingConfirm', ko:'상차 (Chain-of-Custody)', cols:[
    ['LoadingID','INT IDENTITY','PK'],
    ['LoadingNumber','VARCHAR(24)',''],
    ['ShipmentOrderID','INT','FK:FG_ShipmentOrder.ShipmentOrderID'],
    ['PickID','INT','FK:FG_PickingFifo.PickID'],
    ['LicensePlate','VARCHAR(20)',''],
    ['CarrierCode','VARCHAR(20)',''],
    ['DriverID','VARCHAR(30)',''],
    ['DriverName','VARCHAR(50)',''],
    ['DriverPhone','VARCHAR(30)',''],
    ['DockNo','VARCHAR(10)',''],
    ['ArrivalTS','DATETIME2',''],
    ['DepartureTS','DATETIME2',''],
    ['PalletsLoadedJSON','NVARCHAR(MAX)',''],
    ['SealNo','VARCHAR(20)',''],
    ['DriverSigURL','VARCHAR(255)',''],
    ['DriverPhotoURL','VARCHAR(255)',''],
    ['GPSCoord','VARCHAR(30)',''],
    ['OTDStatus','VARCHAR(10)',''],
    ['OperatorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ConfirmedAt','DATETIME2','']
  ]},
  {name:'FG_DeliveryNote', ko:'★ 거래명세서 / BOL', cols:[
    ['DeliveryNoteID','INT IDENTITY','PK'],
    ['DnNumber','VARCHAR(30)',''],
    ['ShipmentOrderID','INT','FK:FG_ShipmentOrder.ShipmentOrderID'],
    ['LoadingID','INT','FK:FG_LoadingConfirm.LoadingID'],
    ['CustomerCode','VARCHAR(20)',''],
    ['FormatTemplate','VARCHAR(40)',''],
    ['Revision','INT',''],
    ['RevisionReason','NVARCHAR(200)',''],
    ['IssuedAt','DATETIME2',''],
    ['IssuedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['PdfUrl','VARCHAR(255)',''],
    ['EdiMsgID','VARCHAR(40)',''],
    ['EdiStatus','VARCHAR(15)',''],
    ['CustomerAckTS','DATETIME2',''],
    ['LinesJSON','NVARCHAR(MAX)','']
  ]},
  {name:'FG_DayEndClose', ko:'일 마감 스냅샷', cols:[
    ['DayEndCloseID','INT IDENTITY','PK'],
    ['CloseNumber','VARCHAR(24)',''],
    ['CloseDate','DATE',''],
    ['ClosedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ClosedAt','DATETIME2',''],
    ['CloseMode','VARCHAR(20)',''],
    ['ChecklistJSON','NVARCHAR(MAX)',''],
    ['KpiJSON','NVARCHAR(MAX)',''],
    ['PendingItemsJSON','NVARCHAR(MAX)',''],
    ['SnapshotURL','VARCHAR(255)',''],
    ['ErpFeedTS','DATETIME2',''],
    ['ErpFeedStatus','VARCHAR(15)','']
  ]},
  {name:'FG_CustomerReturn', ko:'고객 반품 (RMA)', cols:[
    ['ReturnID','INT IDENTITY','PK'],
    ['ReturnNumber','VARCHAR(24)',''],
    ['RMANo','VARCHAR(40)',''],
    ['CustomerCode','VARCHAR(20)',''],
    ['CustomerClaimID','VARCHAR(24)',''],
    ['OriginalShipmentOrderID','INT','FK:FG_ShipmentOrder.ShipmentOrderID'],
    ['OriginalDeliveryNoteID','INT','FK:FG_DeliveryNote.DeliveryNoteID'],
    ['ReturnReason','VARCHAR(60)',''],
    ['ItemsJSON','NVARCHAR(MAX)',''],
    ['Status','VARCHAR(15)',''],
    ['ReceivedAt','DATETIME2',''],
    ['ReceivedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['NcrID','INT','FK:QC_NCR.NcrID'],
    ['CapaTriggered','BIT',''],
    ['ClosedAt','DATETIME2',''],
    ['ClosedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'FG_ReturnDisposition', ko:'반품 처분', cols:[
    ['ReturnDispositionID','INT IDENTITY','PK'],
    ['ReturnID','INT','FK:FG_CustomerReturn.ReturnID'],
    ['PalletSeq','INT',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['Qty','DECIMAL(12,3)',''],
    ['Action','VARCHAR(15)',''],
    ['Reason','NVARCHAR(500)',''],
    ['DownstreamRefID','VARCHAR(24)',''],
    ['ApprovedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApprovedAt','DATETIME2','']
  ]}
]},

// ──────────────────────────────────────────────────────────────────────
// MNT · Maintenance (10 tables)
// ──────────────────────────────────────────────────────────────────────
MNT: { cols: 3, tables: [
  {name:'MNT_EquipmentStatus', ko:'설비 실시간 상태', cols:[
    ['EquipStatusID','INT IDENTITY','PK'],
    ['EquipID','VARCHAR(20)','FK:MD_Equipment.EquipID'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['Status','VARCHAR(10)',''],
    ['TodayOEE','DECIMAL(5,2)',''],
    ['RuntimeHours','DECIMAL(10,1)',''],
    ['CycleCount','BIGINT',''],
    ['NextPMDate','DATE',''],
    ['MountedMoldID','VARCHAR(20)','FK:MD_Mold.MoldID'],
    ['LastFailureID','INT','FK:MNT_FailureRegister.FailureID'],
    ['OpenWoID','INT','FK:MNT_WorkOrder.WorkOrderID'],
    ['PLCConnTS','DATETIME2','']
  ]},
  {name:'MNT_FailureRegister', ko:'★ 고장 등록', cols:[
    ['FailureID','INT IDENTITY','PK'],
    ['FailureNumber','VARCHAR(24)',''],
    ['EquipID','VARCHAR(20)','FK:MD_Equipment.EquipID'],
    ['FailureType','VARCHAR(15)',''],
    ['Symptom','NVARCHAR(500)',''],
    ['Urgency','VARCHAR(10)',''],
    ['PhotoURLs','NVARCHAR(MAX)',''],
    ['Source','VARCHAR(15)',''],
    ['AndonRefID','VARCHAR(24)',''],
    ['WorkOrderID','INT','FK:MNT_WorkOrder.WorkOrderID'],
    ['DowntimeID','INT','FK:PP_LineDowntimeLog.DowntimeID'],
    ['Status','VARCHAR(15)',''],
    ['ReportedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ReportedAt','DATETIME2',''],
    ['ResolvedAt','DATETIME2','']
  ]},
  {name:'MNT_FailureAction', ko:'고장 조치 이력', cols:[
    ['FailureActionID','INT IDENTITY','PK'],
    ['FailureID','INT','FK:MNT_FailureRegister.FailureID'],
    ['ActionType','VARCHAR(20)',''],
    ['Description','NVARCHAR(500)',''],
    ['EvidenceURL','VARCHAR(255)',''],
    ['TechnicianID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ActionAt','DATETIME2','']
  ]},
  {name:'MNT_OEELog', ko:'OEE 측정 (설비×시각)', cols:[
    ['OEELogID','INT IDENTITY','PK'],
    ['OEERecordNumber','VARCHAR(40)',''],
    ['EquipID','VARCHAR(20)','FK:MD_Equipment.EquipID'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['AggLevel','VARCHAR(10)',''],
    ['AggDate','DATE',''],
    ['ShiftCode','VARCHAR(10)',''],
    ['PlannedTimeMin','INT',''],
    ['DowntimeMin','INT',''],
    ['Availability','DECIMAL(5,2)',''],
    ['Performance','DECIMAL(5,2)',''],
    ['Quality','DECIMAL(5,2)',''],
    ['OEE','DECIMAL(5,2)',''],
    ['GoodQty','DECIMAL(12,3)',''],
    ['TotalQty','DECIMAL(12,3)',''],
    ['LossBreakdownJSON','NVARCHAR(MAX)','']
  ]},
  {name:'MNT_PMSchedule', ko:'PM 일정', cols:[
    ['PMScheduleID','INT IDENTITY','PK'],
    ['PMPlanNumber','VARCHAR(30)',''],
    ['EquipID','VARCHAR(20)','FK:MD_Equipment.EquipID'],
    ['PMType','VARCHAR(60)',''],
    ['CycleBasis','VARCHAR(10)',''],
    ['CycleValue','INT',''],
    ['LastPMDate','DATE',''],
    ['NextDueDate','DATE',''],
    ['ChecklistID','VARCHAR(20)','FK:MD_PmTemplate.PMTemplateID'],
    ['AssignedTechID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['Status','VARCHAR(10)',''],
    ['ActiveWoID','INT','FK:MNT_WorkOrder.WorkOrderID']
  ]},
  {name:'MNT_PMExecution', ko:'PM 실행 이력', cols:[
    ['PMExecutionID','INT IDENTITY','PK'],
    ['PMScheduleID','INT','FK:MNT_PMSchedule.PMScheduleID'],
    ['WorkOrderID','INT','FK:MNT_WorkOrder.WorkOrderID'],
    ['CompletedAt','DATETIME2',''],
    ['TechnicianID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['Result','VARCHAR(15)',''],
    ['ResultNote','NVARCHAR(500)',''],
    ['ChecklistResultsJSON','NVARCHAR(MAX)','']
  ]},
  {name:'MNT_WorkOrder', ko:'★ 정비 WO', cols:[
    ['WorkOrderID','INT IDENTITY','PK'],
    ['WoNumber','VARCHAR(28)',''],
    ['WoType','VARCHAR(15)',''],
    ['EquipID','VARCHAR(20)','FK:MD_Equipment.EquipID'],
    ['Priority','VARCHAR(10)',''],
    ['SourceType','VARCHAR(15)',''],
    ['SourceRefID','VARCHAR(24)',''],
    ['AssignedTechID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ChecklistID','VARCHAR(20)','FK:MD_PmTemplate.PMTemplateID'],
    ['ChecklistResultsJSON','NVARCHAR(MAX)',''],
    ['PartsUsedJSON','NVARCHAR(MAX)',''],
    ['LaborMinutes','INT',''],
    ['ActionDesc','NVARCHAR(1000)',''],
    ['Status','VARCHAR(15)',''],
    ['IssuedAt','DATETIME2',''],
    ['StartedAt','DATETIME2',''],
    ['CompletedAt','DATETIME2',''],
    ['ClosedAt','DATETIME2',''],
    ['DowntimeID','INT','FK:PP_LineDowntimeLog.DowntimeID']
  ]},
  {name:'MNT_WorkOrderTask', ko:'정비 WO 작업 항목', cols:[
    ['WorkOrderTaskID','INT IDENTITY','PK'],
    ['WorkOrderID','INT','FK:MNT_WorkOrder.WorkOrderID'],
    ['TaskSeq','INT',''],
    ['TaskName','NVARCHAR(120)',''],
    ['TaskType','VARCHAR(20)',''],
    ['Result','VARCHAR(10)',''],
    ['Note','NVARCHAR(500)',''],
    ['EvidenceURL','VARCHAR(255)',''],
    ['CompletedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['CompletedAt','DATETIME2','']
  ]},
  {name:'MNT_SparePartsTxn', ko:'정비 자재 입출고', cols:[
    ['SparePartsTxnID','INT IDENTITY','PK'],
    ['PartNo','VARCHAR(20)','FK:MD_SparePart.PartNo'],
    ['PartName','NVARCHAR(60)',''],
    ['Category','VARCHAR(15)',''],
    ['MoveType','VARCHAR(10)',''],
    ['Qty','INT',''],
    ['BalanceAfter','INT',''],
    ['UnitPrice','DECIMAL(12,2)',''],
    ['StorageLoc','VARCHAR(20)',''],
    ['RefType','VARCHAR(15)',''],
    ['RefID','VARCHAR(24)',''],
    ['SupplierCode','VARCHAR(20)','FK:MD_Vendor.VendorID'],
    ['Note','NVARCHAR(500)',''],
    ['TxnAt','DATETIME2',''],
    ['ActorID','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'MNT_MoldShotCount', ko:'금형 쇼트 운영 카운터', cols:[
    ['MoldShotCountID','INT IDENTITY','PK'],
    ['MoldID','VARCHAR(20)','FK:MD_Mold.MoldID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['CurrentShots','INT',''],
    ['LifetimeShots','INT',''],
    ['Status','VARCHAR(15)',''],
    ['MountedEquipID','VARCHAR(20)','FK:MD_Equipment.EquipID'],
    ['StorageLoc','VARCHAR(20)',''],
    ['ThresholdLevel','VARCHAR(15)',''],
    ['LastRefurbishTS','DATETIME2',''],
    ['RefurbishCount','INT',''],
    ['HistoryJSON','NVARCHAR(MAX)','']
  ]}
]},

// ──────────────────────────────────────────────────────────────────────
// SYS · System Administration (9 tables)
// ──────────────────────────────────────────────────────────────────────
SYS: { cols: 3, tables: [
  {name:'SYS_UserProfile', ko:'사용자 추가 속성', cols:[
    ['UserProfileID','INT IDENTITY','PK'],
    ['UserID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['EmployeeNo','VARCHAR(20)',''],
    ['EmployeeName','NVARCHAR(50)',''],
    ['Department','VARCHAR(30)',''],
    ['Plant','VARCHAR(20)',''],
    ['DefaultShift','VARCHAR(10)',''],
    ['AssignedLines','NVARCHAR(MAX)',''],
    ['AccountStatus','VARCHAR(10)',''],
    ['FailedLoginCount','INT',''],
    ['LastLoginTS','DATETIME2','']
  ]},
  {name:'SYS_RolePermission', ko:'★ RBAC 매트릭스', cols:[
    ['RolePermissionID','INT IDENTITY','PK'],
    ['RoleID','NVARCHAR(450)','FK:AspNetRoles.Id'],
    ['RoleName','VARCHAR(40)',''],
    ['ModuleCode','VARCHAR(10)',''],
    ['ScreenCode','VARCHAR(20)',''],
    ['PermissionLevel','VARCHAR(10)',''],
    ['IsSystemRole','BIT',''],
    ['EffectiveTS','DATETIME2',''],
    ['ModifiedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'SYS_AuditLog', ko:'★ 감사 로그 (append-only)', cols:[
    ['LogID','BIGINT IDENTITY','PK'],
    ['EventTS','DATETIME2',''],
    ['ActorUserID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ModuleCode','VARCHAR(10)',''],
    ['ScreenCode','VARCHAR(20)',''],
    ['ActionType','VARCHAR(15)',''],
    ['TargetEntity','VARCHAR(40)',''],
    ['TargetID','VARCHAR(40)',''],
    ['BeforeValueJSON','NVARCHAR(MAX)',''],
    ['AfterValueJSON','NVARCHAR(MAX)',''],
    ['IPAddress','VARCHAR(45)',''],
    ['Result','VARCHAR(10)',''],
    ['Note','NVARCHAR(500)','']
  ]},
  {name:'SYS_NotificationRule', ko:'알림 규칙', cols:[
    ['NotificationRuleID','INT IDENTITY','PK'],
    ['EventTypeCode','VARCHAR(20)',''],
    ['EventName','NVARCHAR(60)',''],
    ['SourceModule','VARCHAR(10)',''],
    ['TriggerCondition','NVARCHAR(500)',''],
    ['IsEnabled','BIT',''],
    ['ChannelsJSON','NVARCHAR(200)',''],
    ['RecipientRolesJSON','NVARCHAR(500)',''],
    ['ModifiedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'SYS_NotificationChannel', ko:'사용자별 알림 채널', cols:[
    ['NotificationChannelID','INT IDENTITY','PK'],
    ['UserID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['Channel','VARCHAR(10)',''],
    ['Address','VARCHAR(255)',''],
    ['IsEnabled','BIT',''],
    ['QuietHoursStart','TIME',''],
    ['QuietHoursEnd','TIME',''],
    ['VerifiedAt','DATETIME2','']
  ]},
  {name:'SYS_NotificationHistory', ko:'알림 발송 이력', cols:[
    ['NotificationHistoryID','BIGINT IDENTITY','PK'],
    ['NotificationRuleID','INT','FK:SYS_NotificationRule.NotificationRuleID'],
    ['EventTypeCode','VARCHAR(20)',''],
    ['RecipientUserID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['Channel','VARCHAR(10)',''],
    ['Address','VARCHAR(255)',''],
    ['Subject','NVARCHAR(200)',''],
    ['Body','NVARCHAR(MAX)',''],
    ['SourceRefType','VARCHAR(20)',''],
    ['SourceRefID','VARCHAR(40)',''],
    ['Status','VARCHAR(15)',''],
    ['RetryCount','INT',''],
    ['SentAt','DATETIME2',''],
    ['ReadAt','DATETIME2',''],
    ['ErrorMsg','NVARCHAR(500)','']
  ]},
  {name:'SYS_Config', ko:'환경설정 (Key-Value)', cols:[
    ['ConfigID','INT IDENTITY','PK'],
    ['ConfigKey','VARCHAR(60)',''],
    ['ConfigType','VARCHAR(15)',''],
    ['Category','VARCHAR(30)',''],
    ['ConfigValue','NVARCHAR(500)',''],
    ['CodeName','NVARCHAR(80)',''],
    ['Unit','VARCHAR(10)',''],
    ['UsedByModulesJSON','NVARCHAR(500)',''],
    ['SortOrder','INT',''],
    ['IsActive','BIT',''],
    ['ModifiedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'SYS_InterfaceMonitor', ko:'인터페이스 상태', cols:[
    ['InterfaceMonitorID','INT IDENTITY','PK'],
    ['InterfaceCode','VARCHAR(20)',''],
    ['InterfaceName','NVARCHAR(60)',''],
    ['Direction','VARCHAR(15)',''],
    ['Endpoint','VARCHAR(255)',''],
    ['Protocol','VARCHAR(15)',''],
    ['ConnStatus','VARCHAR(10)',''],
    ['LastSyncTS','DATETIME2',''],
    ['MaxGapMinutes','INT',''],
    ['LastRecordCount','INT',''],
    ['RetryCount','INT',''],
    ['LastErrorMsg','NVARCHAR(1000)',''],
    ['IsEnabled','BIT','']
  ]},
  {name:'SYS_FactoryCalendar', ko:'공장 캘린더 (교대 인스턴스)', cols:[
    ['FactoryCalendarID','INT IDENTITY','PK'],
    ['CalendarDate','DATE',''],
    ['DayType','VARCHAR(10)',''],
    ['HolidayName','NVARCHAR(40)',''],
    ['ShiftCount','INT',''],
    ['ShiftCode','VARCHAR(10)',''],
    ['StartTime','TIME',''],
    ['EndTime','TIME',''],
    ['BreakMinutes','INT',''],
    ['NetWorkHours','DECIMAL(4,1)',''],
    ['CalendarYear','INT',''],
    ['Plant','VARCHAR(20)','']
  ]}
]},

// ──────────────────────────────────────────────────────────────────────
// ID · ASP.NET Identity (7 tables, standard EF Core schema)
// ──────────────────────────────────────────────────────────────────────
ID: { cols: 3, tables: [
  {name:'AspNetUsers', ko:'★ 사용자', cols:[
    ['Id','NVARCHAR(450)','PK'],
    ['UserName','NVARCHAR(256)',''],
    ['NormalizedUserName','NVARCHAR(256)',''],
    ['Email','NVARCHAR(256)',''],
    ['NormalizedEmail','NVARCHAR(256)',''],
    ['EmailConfirmed','BIT',''],
    ['PasswordHash','NVARCHAR(MAX)',''],
    ['SecurityStamp','NVARCHAR(MAX)',''],
    ['ConcurrencyStamp','NVARCHAR(MAX)',''],
    ['PhoneNumber','NVARCHAR(MAX)',''],
    ['PhoneNumberConfirmed','BIT',''],
    ['TwoFactorEnabled','BIT',''],
    ['LockoutEnd','DATETIMEOFFSET',''],
    ['LockoutEnabled','BIT',''],
    ['AccessFailedCount','INT','']
  ]},
  {name:'AspNetRoles', ko:'역할', cols:[
    ['Id','NVARCHAR(450)','PK'],
    ['Name','NVARCHAR(256)',''],
    ['NormalizedName','NVARCHAR(256)',''],
    ['ConcurrencyStamp','NVARCHAR(MAX)','']
  ]},
  {name:'AspNetUserRoles', ko:'사용자×역할', cols:[
    ['UserId','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['RoleId','NVARCHAR(450)','FK:AspNetRoles.Id']
  ]},
  {name:'AspNetUserClaims', ko:'사용자 클레임', cols:[
    ['Id','INT IDENTITY','PK'],
    ['UserId','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ClaimType','NVARCHAR(MAX)',''],
    ['ClaimValue','NVARCHAR(MAX)','']
  ]},
  {name:'AspNetUserLogins', ko:'외부 로그인', cols:[
    ['LoginProvider','NVARCHAR(450)','PK'],
    ['ProviderKey','NVARCHAR(450)','PK'],
    ['ProviderDisplayName','NVARCHAR(MAX)',''],
    ['UserId','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'AspNetUserTokens', ko:'사용자 토큰', cols:[
    ['UserId','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['LoginProvider','NVARCHAR(450)','PK'],
    ['Name','NVARCHAR(450)','PK'],
    ['Value','NVARCHAR(MAX)','']
  ]},
  {name:'AspNetRoleClaims', ko:'역할 클레임', cols:[
    ['Id','INT IDENTITY','PK'],
    ['RoleId','NVARCHAR(450)','FK:AspNetRoles.Id'],
    ['ClaimType','NVARCHAR(MAX)',''],
    ['ClaimValue','NVARCHAR(MAX)','']
  ]}
]}

};

