// ════════════════════════════════════════════════════════════════════════
//  A-MES ERD Data · 149 tables across 10 modules
//  Column format: [name, type, flag]
//    flag = '' | 'PK' | 'FK:Target.Column'
//  External FKs render as dashed chips automatically.
// ════════════════════════════════════════════════════════════════════════
const ERD_DATA = {

// ──────────────────────────────────────────────────────────────────────
// MD · Master Data (33 tables, natural-key PKs)
// ──────────────────────────────────────────────────────────────────────
MD: { cols: 4, tables: [
  {name:'MD_Item', ko:'품목 (MD-01)', cols:[
    ['ItemNo','VARCHAR(20)','PK'],
    ['ItemName','NVARCHAR(80)',''],
    ['ItemNameEN','NVARCHAR(80)',''],
    ['ItemType','VARCHAR(10)',''],
    ['ItemCategory','VARCHAR(30)',''],
    ['DefaultUOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['RoutingType','CHAR(1)',''],
    ['MinStock','DECIMAL(14,4)',''],
    ['MaxStock','DECIMAL(14,4)',''],
    ['SafetyStock','DECIMAL(14,4)',''],
    ['UnitCost','DECIMAL(14,2)',''],
    ['CustItemNoSAV','VARCHAR(30)',''],
    ['CustItemNoGEO','VARCHAR(30)',''],
    ['DrawingNo','VARCHAR(30)',''],
    ['ActiveFlag','BIT',''],
    ['CreatedBy','VARCHAR(20)',''],
    ['CreatedTS','DATETIME2',''],
    ['ModifiedTS','DATETIME2','']
  ]},
  {name:'MD_Bom', ko:'BOM (MD-02)', cols:[
    ['BOMID','VARCHAR(24)','PK'],
    ['ParentItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['CompItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['BOMLevel','INT',''],
    ['QtyPer','DECIMAL(12,4)',''],
    ['UOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['ScrapPct','DECIMAL(5,2)',''],
    ['VersionID','VARCHAR(24)','FK:MD_BomVersion.VersionID'],
    ['Position','INT',''],
    ['Note','NVARCHAR(120)',''],
    ['ActiveFlag','BIT',''],
    ['CreatedTS','DATETIME2','']
  ]},
  {name:'MD_BomVersion', ko:'BOM 버전 (MD-03)', cols:[
    ['VersionID','VARCHAR(24)','PK'],
    ['RootItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['VersionNo','VARCHAR(10)',''],
    ['EffFrom','DATE',''],
    ['EffTo','DATE',''],
    ['ChangeType','VARCHAR(16)',''],
    ['ChangeReason','NVARCHAR(200)',''],
    ['RequestedBy','VARCHAR(20)',''],
    ['ApprovedBy','VARCHAR(20)',''],
    ['ApprovedTS','DATETIME2',''],
    ['Status','VARCHAR(12)','']
  ]},
  {name:'MD_Bop', ko:'BOP 라우팅 (MD-04)', cols:[
    ['BOPID','VARCHAR(24)','PK'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['RoutingType','CHAR(1)',''],
    ['StepSeq','INT',''],
    ['ProcessCode','VARCHAR(10)',''],
    ['WorkCenterID','VARCHAR(20)','FK:MD_WorkCenter.WCID'],
    ['StdCycleTime','DECIMAL(8,2)',''],
    ['StdSetupTime','DECIMAL(8,2)',''],
    ['QcRequiredFlag','BIT',''],
    ['StepDescription','NVARCHAR(120)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_WorkCenter', ko:'작업장 (MD-05)', cols:[
    ['WCID','VARCHAR(20)','PK'],
    ['WCName','NVARCHAR(50)',''],
    ['ProcessType','VARCHAR(16)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['DailyCapacity','INT',''],
    ['StdManpower','INT',''],
    ['CostCenterCode','VARCHAR(20)',''],
    ['LocationDesc','NVARCHAR(60)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_InspectionStandard', ko:'검사 기준 (MD-06)', cols:[
    ['InspStdID','VARCHAR(20)','PK'],
    ['ItemID','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['ProcessCode','VARCHAR(10)',''],
    ['InspType','VARCHAR(10)',''],
    ['CharName','NVARCHAR(60)',''],
    ['SpecNominal','DECIMAL(12,4)',''],
    ['SpecLSL','DECIMAL(12,4)',''],
    ['SpecUSL','DECIMAL(12,4)',''],
    ['UOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['SamplingPlan','VARCHAR(20)',''],
    ['InspMethod','NVARCHAR(40)',''],
    ['IsCTQ','BIT',''],
    ['EffectiveDate','DATE',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_Vendor', ko:'거래선 (MD-07)', cols:[
    ['VendorID','VARCHAR(20)','PK'],
    ['VendorName','NVARCHAR(80)',''],
    ['VendorType','VARCHAR(10)',''],
    ['VendorCategory','NVARCHAR(30)',''],
    ['BizRegNo','VARCHAR(20)',''],
    ['ContactPerson','NVARCHAR(40)',''],
    ['Phone','VARCHAR(20)',''],
    ['Email','VARCHAR(60)',''],
    ['ScmURL','VARCHAR(255)',''],
    ['EdiFlag','BIT',''],
    ['OtdTargetRate','DECIMAL(5,2)',''],
    ['PaymentTerms','VARCHAR(30)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_Equipment', ko:'설비 (MD-08)', cols:[
    ['EquipID','VARCHAR(20)','PK'],
    ['EquipName','NVARCHAR(50)',''],
    ['EquipType','VARCHAR(16)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['WCID','VARCHAR(20)','FK:MD_WorkCenter.WCID'],
    ['MakerModel','NVARCHAR(60)',''],
    ['InstallDate','DATE',''],
    ['TheoreticalCycle','DECIMAL(8,2)',''],
    ['TargetOEE','DECIMAL(5,2)',''],
    ['MoldCompatJSON','NVARCHAR(MAX)',''],
    ['PlcAddress','VARCHAR(40)',''],
    ['Status','VARCHAR(8)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_Mold', ko:'금형 (MD-09)', cols:[
    ['MoldID','VARCHAR(20)','PK'],
    ['MoldName','NVARCHAR(50)',''],
    ['CompatItemsJSON','NVARCHAR(MAX)',''],
    ['RatedShots','INT',''],
    ['CurrentShots','INT',''],
    ['CavityCount','INT',''],
    ['Tonnage','INT',''],
    ['StorageLoc','VARCHAR(20)',''],
    ['LastMaintDate','DATE',''],
    ['Status','VARCHAR(10)','']
  ]},
  {name:'MD_PaintFabric', ko:'도료·원단 LOT (MD-10)', cols:[
    ['MatLotID','VARCHAR(24)','PK'],
    ['MatCode','VARCHAR(20)',''],
    ['MatName','NVARCHAR(60)',''],
    ['MatType','VARCHAR(14)',''],
    ['LotNo','VARCHAR(24)',''],
    ['SupplierID','VARCHAR(20)','FK:MD_Vendor.VendorID'],
    ['UOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['QtyOnHand','DECIMAL(12,3)',''],
    ['ReceiptDate','DATE',''],
    ['ExpDate','DATE',''],
    ['StorageReq','NVARCHAR(40)',''],
    ['Status','VARCHAR(10)','']
  ]},
  {name:'MD_ShipmentDest', ko:'출하처 (MD-11)', cols:[
    ['ShipDestID','VARCHAR(20)','PK'],
    ['CustomerID','VARCHAR(20)','FK:MD_Customer.CustomerID'],
    ['DestName','NVARCHAR(80)',''],
    ['DestType','VARCHAR(10)',''],
    ['Address','NVARCHAR(200)',''],
    ['Country','CHAR(3)',''],
    ['DeliveryDock','VARCHAR(20)',''],
    ['LeadTimeDays','INT',''],
    ['DefaultCarrier','NVARCHAR(40)',''],
    ['DeliveryWindow','VARCHAR(40)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_Customer', ko:'고객사 (MD-12)', cols:[
    ['CustomerID','VARCHAR(20)','PK'],
    ['CustomerCode','VARCHAR(20)',''],
    ['CustomerName','NVARCHAR(80)',''],
    ['CustomerNameEn','NVARCHAR(80)',''],
    ['CustomerType','VARCHAR(12)',''],
    ['BizRegNo','VARCHAR(20)',''],
    ['Country','CHAR(3)',''],
    ['ContactPerson','NVARCHAR(40)',''],
    ['ContactPhone','VARCHAR(20)',''],
    ['ContactEmail','VARCHAR(60)',''],
    ['EDIFlag','BIT',''],
    ['CurrencyCode','CHAR(3)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_Uom', ko:'단위 (MD-13)', cols:[
    ['UOMCode','VARCHAR(10)','PK'],
    ['UOMName','NVARCHAR(30)',''],
    ['UOMCategory','VARCHAR(10)',''],
    ['BaseFlag','BIT',''],
    ['BaseUOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['ConvFactor','DECIMAL(18,8)',''],
    ['DecimalPrec','INT',''],
    ['Symbol','NVARCHAR(8)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_Calendar', ko:'공장 캘린더 (MD-14)', cols:[
    ['PlantID','VARCHAR(10)','PK'],
    ['CalendarDate','DATE','PK'],
    ['DayType','VARCHAR(10)',''],
    ['HolidayName','NVARCHAR(40)',''],
    ['ShiftCount','INT',''],
    ['ShiftPattern','VARCHAR(20)',''],
    ['WorkHours','DECIMAL(5,2)',''],
    ['CalendarYear','INT',''],
    ['Note','NVARCHAR(120)','']
  ]},
  {name:'MD_Jig', ko:'지그 (MD-15)', cols:[
    ['JigID','VARCHAR(20)','PK'],
    ['JigName','NVARCHAR(50)',''],
    ['HangerCount','INT',''],
    ['CompatItemsJSON','NVARCHAR(MAX)',''],
    ['RatedCycle','INT',''],
    ['CycleCount','INT',''],
    ['ReadFailRate','DECIMAL(5,2)',''],
    ['HealthStatus','VARCHAR(8)',''],
    ['LastServiceDate','DATE',''],
    ['LastUsedTS','DATETIME2',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_RfidTag', ko:'RFID 태그 (MD-16)', cols:[
    ['TagID','VARCHAR(24)','PK'],
    ['EPC','VARCHAR(32)',''],
    ['JigID','VARCHAR(20)','FK:MD_Jig.JigID'],
    ['TagRole','VARCHAR(6)',''],
    ['HeatRating','INT',''],
    ['MountPos','NVARCHAR(20)',''],
    ['InstallDate','DATE',''],
    ['CycleCount','INT',''],
    ['ReplaceSchedule','DATE',''],
    ['Status','VARCHAR(10)','']
  ]},
  {name:'MD_RalColor', ko:'RAL 컬러 (MD-17)', cols:[
    ['RALCode','VARCHAR(12)','PK'],
    ['ColorName','NVARCHAR(40)',''],
    ['HexValue','VARCHAR(7)',''],
    ['CurrentPowderLot','VARCHAR(24)','FK:MD_PaintFabric.MatLotID'],
    ['CureTemp','INT',''],
    ['CureDuration','INT',''],
    ['ElectroV','INT',''],
    ['ParticleUm','DECIMAL(5,1)',''],
    ['CustomerMapJSON','NVARCHAR(MAX)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_Oven', ko:'오븐 (MD-18)', cols:[
    ['OvenID','VARCHAR(20)','PK'],
    ['OvenName','NVARCHAR(50)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['ZoneCount','INT',''],
    ['TargetTemp','INT',''],
    ['Tolerance','INT',''],
    ['DwellSec','INT',''],
    ['ConveyorSpeed','DECIMAL(6,2)',''],
    ['MaxLoadKg','DECIMAL(8,1)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_RfidReader', ko:'RFID 리더 (MD-19)', cols:[
    ['ReaderID','VARCHAR(20)','PK'],
    ['ReaderName','NVARCHAR(50)',''],
    ['GateLocation','VARCHAR(4)',''],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['AntennaCount','INT',''],
    ['PowerDbm','INT',''],
    ['PeTriggerFlag','BIT',''],
    ['WindowMs','INT',''],
    ['IpAddress','VARCHAR(45)',''],
    ['FirmwareVer','VARCHAR(16)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_Line', ko:'생산 라인 (MD-20)', cols:[
    ['LineID','VARCHAR(20)','PK'],
    ['LineName','NVARCHAR(50)',''],
    ['LineType','VARCHAR(16)',''],
    ['PlantID','VARCHAR(10)',''],
    ['DefaultWCID','VARCHAR(20)','FK:MD_WorkCenter.WCID'],
    ['DailyCap','INT',''],
    ['ShiftPattern','VARCHAR(20)',''],
    ['RfidEnabledFlag','BIT',''],
    ['Status','VARCHAR(10)','']
  ]},
  {name:'MD_DefectCode', ko:'불량 코드 (MD-21)', cols:[
    ['DefectCode','VARCHAR(16)','PK'],
    ['DefectName','NVARCHAR(60)',''],
    ['DefectNameEn','NVARCHAR(60)',''],
    ['ProcessCode','VARCHAR(10)',''],
    ['DefectCategory','VARCHAR(14)',''],
    ['SeverityLevel','VARCHAR(8)',''],
    ['DispositionDefault','VARCHAR(10)',''],
    ['DefaultCauseCode','VARCHAR(16)','FK:MD_DefectCause.CauseCode'],
    ['ParetoFlag','BIT',''],
    ['ImageRef','VARCHAR(120)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_DefectCause', ko:'불량 원인 (MD-22)', cols:[
    ['CauseCode','VARCHAR(16)','PK'],
    ['CauseName','NVARCHAR(60)',''],
    ['CauseCategory','VARCHAR(9)',''],
    ['ParentCauseCode','VARCHAR(16)','FK:MD_DefectCause.CauseCode'],
    ['ProcessCode','VARCHAR(10)',''],
    ['RootCauseFlag','BIT',''],
    ['CorrectiveGuide','NVARCHAR(200)',''],
    ['ResponsibleDept','NVARCHAR(30)',''],
    ['SortOrder','INT',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_PackagingSpec', ko:'포장 사양 (MD-23)', cols:[
    ['PackSpecID','VARCHAR(20)','PK'],
    ['ItemID','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['PackType','VARCHAR(12)',''],
    ['QtyPerInner','INT',''],
    ['InnerPerOuter','INT',''],
    ['OuterPerPallet','INT',''],
    ['NetWeightKg','DECIMAL(8,3)',''],
    ['GrossWeightKg','DECIMAL(8,3)',''],
    ['DimLxWxH','VARCHAR(30)',''],
    ['ReturnableFlag','BIT',''],
    ['LabelTemplateID','VARCHAR(20)','FK:MD_LabelTemplate.LabelTemplateID'],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_LabelTemplate', ko:'라벨 템플릿 (MD-24)', cols:[
    ['LabelTemplateID','VARCHAR(20)','PK'],
    ['TemplateName','NVARCHAR(60)',''],
    ['LabelType','VARCHAR(12)',''],
    ['PaperSize','VARCHAR(12)',''],
    ['BarcodeType','VARCHAR(12)',''],
    ['LayoutZPL','NVARCHAR(MAX)',''],
    ['FieldMapJSON','NVARCHAR(MAX)',''],
    ['CustomerID','VARCHAR(20)','FK:MD_Customer.CustomerID'],
    ['Version','INT',''],
    ['PrinterModel','VARCHAR(30)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_ReasonCode', ko:'사유 코드 (MD-25)', cols:[
    ['ReasonCode','VARCHAR(16)','PK'],
    ['ReasonName','NVARCHAR(60)',''],
    ['ReasonType','VARCHAR(12)',''],
    ['AppliesToModule','VARCHAR(10)',''],
    ['RequiresComment','BIT',''],
    ['PlannedFlag','BIT',''],
    ['DisplayOrder','INT',''],
    ['Description','NVARCHAR(120)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_CodeGroup', ko:'공통코드 그룹 (MD-26a)', cols:[
    ['GroupCode','VARCHAR(20)','PK'],
    ['GroupName','NVARCHAR(60)',''],
    ['GroupNameEn','NVARCHAR(60)',''],
    ['Description','NVARCHAR(200)',''],
    ['UseFlag','BIT','']
  ]},
  {name:'MD_CodeItem', ko:'공통코드 항목 (MD-26b)', cols:[
    ['CodeID','VARCHAR(24)','PK'],
    ['GroupCode','VARCHAR(20)','FK:MD_CodeGroup.GroupCode'],
    ['CodeValue','VARCHAR(20)',''],
    ['CodeName','NVARCHAR(60)',''],
    ['CodeNameEn','NVARCHAR(60)',''],
    ['ParentCodeID','VARCHAR(24)','FK:MD_CodeItem.CodeID'],
    ['SortOrder','INT',''],
    ['Attribute1','NVARCHAR(40)',''],
    ['UseFlag','BIT',''],
    ['Description','NVARCHAR(120)','']
  ]},
  {name:'MD_SparePart', ko:'정비 자재 (MD-27)', cols:[
    ['PartNo','VARCHAR(20)','PK'],
    ['PartName','NVARCHAR(60)',''],
    ['Category','VARCHAR(16)',''],
    ['CompatEquipJSON','NVARCHAR(MAX)',''],
    ['UnitCost','DECIMAL(12,2)',''],
    ['UOM','VARCHAR(10)','FK:MD_Uom.UOMCode'],
    ['SafetyStock','INT',''],
    ['ReorderPoint','INT',''],
    ['ReorderQty','INT',''],
    ['LeadTimeDays','INT',''],
    ['SupplierID','VARCHAR(20)','FK:MD_Vendor.VendorID'],
    ['StorageLoc','VARCHAR(20)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_PmTemplate', ko:'PM 템플릿 (MD-28a)', cols:[
    ['PMTemplateID','VARCHAR(20)','PK'],
    ['TemplateName','NVARCHAR(60)',''],
    ['EquipType','VARCHAR(16)',''],
    ['CycleBasis','VARCHAR(10)',''],
    ['IntervalValue','INT',''],
    ['IntervalUnit','VARCHAR(8)',''],
    ['StdDurationMin','INT',''],
    ['SafetyLOTOFlag','BIT',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_PmTemplateStep', ko:'PM 점검 항목 (MD-28b)', cols:[
    ['PMStepID','VARCHAR(24)','PK'],
    ['PMTemplateID','VARCHAR(20)','FK:MD_PmTemplate.PMTemplateID'],
    ['StepSeq','INT',''],
    ['StepDescription','NVARCHAR(200)',''],
    ['AcceptanceCriteria','NVARCHAR(200)',''],
    ['RequiredPartNo','VARCHAR(20)','FK:MD_SparePart.PartNo'],
    ['RequiredQty','DECIMAL(10,3)',''],
    ['StepDurationMin','INT','']
  ]},
  {name:'MD_LineTimePattern', ko:'시간패턴 헤더 (MD-29a)', cols:[
    ['PatternID','VARCHAR(20)','PK'],
    ['LineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['PatternName','NVARCHAR(50)',''],
    ['DayType','VARCHAR(10)',''],
    ['ShiftModel','VARCHAR(12)',''],
    ['EffectiveFrom','DATE',''],
    ['EffectiveTo','DATE',''],
    ['TotalOperatingMin','INT',''],
    ['TotalPlannedDownMin','INT',''],
    ['TimeZone','VARCHAR(20)',''],
    ['Status','VARCHAR(8)','']
  ]},
  {name:'MD_LineTimeSegment', ko:'시간 세그먼트 (MD-29b)', cols:[
    ['SegmentID','VARCHAR(24)','PK'],
    ['PatternID','VARCHAR(20)','FK:MD_LineTimePattern.PatternID'],
    ['SeqNo','INT',''],
    ['StartMin','SMALLINT',''],
    ['EndMin','SMALLINT',''],
    ['SegmentState','VARCHAR(14)',''],
    ['ReasonCode','VARCHAR(16)','FK:MD_ReasonCode.ReasonCode'],
    ['ShiftCode','VARCHAR(10)',''],
    ['Description','NVARCHAR(60)','']
  ]},
  {name:'MD_Location', ko:'로케이션 (보조)', cols:[
    ['LocationID','VARCHAR(20)','PK'],
    ['LocationName','NVARCHAR(60)',''],
    ['ZoneCode','VARCHAR(10)',''],
    ['Aisle','VARCHAR(5)',''],
    ['Bay','VARCHAR(5)',''],
    ['Slot','VARCHAR(5)',''],
    ['Capacity','DECIMAL(10,3)',''],
    ['LocationType','VARCHAR(20)',''],
    ['PlantID','VARCHAR(10)',''],
    ['ActiveFlag','BIT','']
  ]},
  {name:'MD_Recipe', ko:'레시피 (보조)', cols:[
    ['RecipeID','VARCHAR(20)','PK'],
    ['RecipeName','NVARCHAR(60)',''],
    ['RecipeType','VARCHAR(15)',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['CycleTime','INT',''],
    ['ParamsJSON','NVARCHAR(MAX)',''],
    ['Version','VARCHAR(10)',''],
    ['EffectiveDate','DATE',''],
    ['Status','VARCHAR(10)','']
  ]}
]},

// ──────────────────────────────────────────────────────────────────────
// WH · Warehouse (8 tables)
// ──────────────────────────────────────────────────────────────────────
WH: { cols: 3, tables: [
  {name:'WH_PurchaseOrder', ko:'구매발주 (SCM)', cols:[
    ['PoID','INT IDENTITY','PK'],
    ['PoNumber','VARCHAR(20)',''],
    ['PoLineNo','INT',''],
    ['VendorID','VARCHAR(20)','FK:MD_Vendor.VendorID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['OrderQty','DECIMAL(12,3)',''],
    ['ReceivedQty','DECIMAL(12,3)',''],
    ['UnitCode','VARCHAR(10)',''],
    ['UnitPrice','DECIMAL(14,4)',''],
    ['Currency','CHAR(3)',''],
    ['OrderDate','DATE',''],
    ['DueDate','DATE',''],
    ['Status','VARCHAR(20)',''],
    ['SapSyncedAt','DATETIME2',''],
    ['CreatedAt','DATETIME2','']
  ]},
  {name:'WH_Receiving', ko:'입고 실적', cols:[
    ['ReceivingID','INT IDENTITY','PK'],
    ['ReceivingNo','VARCHAR(24)',''],
    ['PoID','INT','FK:WH_PurchaseOrder.PoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['VendorID','VARCHAR(20)','FK:MD_Vendor.VendorID'],
    ['ReceivedQty','DECIMAL(12,3)',''],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotCode','VARCHAR(40)',''],
    ['ReceivedAt','DATETIME2',''],
    ['ReceivedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['TerminalID','VARCHAR(20)',''],
    ['QcStatus','VARCHAR(20)',''],
    ['LabelPrinted','BIT','']
  ]},
  {name:'WH_Inventory', ko:'현재고', cols:[
    ['InventoryID','INT IDENTITY','PK'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['OnHandQty','DECIMAL(14,3)',''],
    ['ReservedQty','DECIMAL(14,3)',''],
    ['UnitCost','DECIMAL(14,4)',''],
    ['LastReceivedAt','DATETIME2',''],
    ['ExpiryDate','DATE',''],
    ['Status','VARCHAR(20)','']
  ]},
  {name:'WH_InventorySnapshot', ko:'재고 일일 스냅샷', cols:[
    ['SnapshotID','BIGINT IDENTITY','PK'],
    ['SnapshotDate','DATE',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['OnHandQty','DECIMAL(14,3)',''],
    ['UnitCost','DECIMAL(14,4)',''],
    ['TotalValue','DECIMAL(16,2)','']
  ]},
  {name:'WH_InventoryAdjust', ko:'재고 조정', cols:[
    ['AdjustID','INT IDENTITY','PK'],
    ['AdjustNo','VARCHAR(24)',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['QtyBefore','DECIMAL(14,3)',''],
    ['Delta','DECIMAL(14,3)',''],
    ['QtyAfter','DECIMAL(14,3)',''],
    ['ReasonCode','VARCHAR(30)',''],
    ['ReasonNote','NVARCHAR(500)',''],
    ['Status','VARCHAR(20)',''],
    ['RequestedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApprovedBy','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'WH_ReleaseSchedule', ko:'출고 예정 (WO 수요)', cols:[
    ['ReleaseScheduleID','INT IDENTITY','PK'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['DemandQty','DECIMAL(14,3)',''],
    ['PickedQty','DECIMAL(14,3)',''],
    ['RequiredAt','DATETIME2',''],
    ['Priority','TINYINT',''],
    ['Status','VARCHAR(20)','']
  ]},
  {name:'WH_ReleasePicking', ko:'출고 피킹', cols:[
    ['PickingID','INT IDENTITY','PK'],
    ['PickingNo','VARCHAR(24)',''],
    ['ReleaseScheduleID','INT','FK:WH_ReleaseSchedule.ReleaseScheduleID'],
    ['WoID','INT','FK:PP_WorkOrder.WoID'],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['PickedQty','DECIMAL(14,3)',''],
    ['DestLineID','VARCHAR(20)','FK:MD_Line.LineID'],
    ['PickedAt','DATETIME2',''],
    ['PickedBy','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['TerminalID','VARCHAR(20)',''],
    ['FifoOverride','BIT',''],
    ['OverrideReason','NVARCHAR(200)',''],
    ['OverrideApprover','NVARCHAR(450)','FK:AspNetUsers.Id']
  ]},
  {name:'WH_TransactionHistory', ko:'입출고 트랜잭션 (append-only)', cols:[
    ['TxnID','BIGINT IDENTITY','PK'],
    ['TxnTime','DATETIME2',''],
    ['TxnType','VARCHAR(10)',''],
    ['ItemNo','VARCHAR(20)','FK:MD_Item.ItemNo'],
    ['LocationID','VARCHAR(20)','FK:MD_Location.LocationID'],
    ['LotID','INT','FK:tbl_Lot.LotID'],
    ['QtyBefore','DECIMAL(14,3)',''],
    ['Delta','DECIMAL(14,3)',''],
    ['QtyAfter','DECIMAL(14,3)',''],
    ['ReasonCode','VARCHAR(30)',''],
    ['RefDocType','VARCHAR(20)',''],
    ['RefDocID','INT',''],
    ['OperatorID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['ApproverID','NVARCHAR(450)','FK:AspNetUsers.Id'],
    ['Note','NVARCHAR(500)','']
  ]}
]},

// Modules to be populated next (placeholders for now)
PP:  { cols: 4, tables: [] },
PR:  { cols: 4, tables: [] },
PNT: { cols: 4, tables: [] },
QC:  { cols: 3, tables: [] },
FG:  { cols: 3, tables: [] },
MNT: { cols: 3, tables: [] },
SYS: { cols: 3, tables: [] },
ID:  { cols: 3, tables: [] }

};
