SET XACT_ABORT ON;
IF DB_NAME() <> N'AMES_DEV' THROW 50000, 'Only AMES_DEV is allowed.', 1;
BEGIN TRANSACTION;
IF OBJECT_ID(N'dbo.TEST_SRM_Shipment', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TEST_SRM_Shipment (
        REQUEST_ID nvarchar(100) COLLATE Latin1_General_100_BIN2 NOT NULL PRIMARY KEY,
        CORCD nvarchar(100) NOT NULL, BIZCD nvarchar(100) NOT NULL,
        VENDCD nvarchar(100) NOT NULL, PURC_ORG nvarchar(100) NOT NULL,
        PURC_PO_TYPE nvarchar(100) NOT NULL,
        DELI_DATE date NOT NULL, ARRIV_DATE date NOT NULL, ARRIV_TIME nvarchar(4) NOT NULL,
        TRUCK_NO nvarchar(100) NOT NULL, USER_ID nvarchar(100) NOT NULL,
        DELI_NOTE nvarchar(100) NOT NULL UNIQUE,
        STATUS nvarchar(100) NOT NULL, SAP_STATUS nvarchar(100) NOT NULL,
        SAP_SIMULATED bit NOT NULL,
        RECEIVED_AT_UTC datetimeoffset(7) NOT NULL,
        ITEM_COUNT int NOT NULL CHECK (ITEM_COUNT BETWEEN 1 AND 1000),
        TOTAL_DELI_QTY decimal(28,6) NOT NULL CHECK (TOTAL_DELI_QTY > 0),
        REQUEST_JSON nvarchar(max) NOT NULL CHECK (ISJSON(REQUEST_JSON)=1),
        RECEIPT_JSON nvarchar(max) NOT NULL CHECK (ISJSON(RECEIPT_JSON)=1),
        CHECK (ARRIV_DATE >= DELI_DATE)
    );
    CREATE INDEX IX_TEST_SRM_Shipment_Date ON dbo.TEST_SRM_Shipment(DELI_DATE, VENDCD);
END;
IF OBJECT_ID(N'dbo.TEST_SRM_ShipmentItem', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TEST_SRM_ShipmentItem (
        REQUEST_ID nvarchar(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
        ITEM_NO int NOT NULL CHECK (ITEM_NO BETWEEN 1 AND 1000),
        PONO nvarchar(100) NOT NULL, PONO_SEQ nvarchar(100) NOT NULL,
        UNIT_PACK_QTY decimal(28,6) NOT NULL CHECK (UNIT_PACK_QTY > 0 AND UNIT_PACK_QTY <= 1000000000),
        DELI_QTY decimal(28,6) NOT NULL CHECK (DELI_QTY > 0 AND DELI_QTY <= 1000000000),
        VEND_LOTNO nvarchar(100) NOT NULL, PRDT_DATE date NOT NULL, CHANGE_4M nvarchar(100) NOT NULL,
        PRIMARY KEY (REQUEST_ID, ITEM_NO),
        FOREIGN KEY (REQUEST_ID) REFERENCES dbo.TEST_SRM_Shipment(REQUEST_ID)
    );
    CREATE INDEX IX_TEST_SRM_ShipmentItem_PO ON dbo.TEST_SRM_ShipmentItem(PONO, PONO_SEQ);
END;
COMMIT;
SELECT N'dbo.TEST_SRM_Shipment' AS TableName, COUNT(*) AS Rows FROM dbo.TEST_SRM_Shipment
UNION ALL SELECT N'dbo.TEST_SRM_ShipmentItem', COUNT(*) FROM dbo.TEST_SRM_ShipmentItem;
